// @generated by scripts/gen_syscalls.py from crates/core/src/proc/syscalls.toml.
// Do not edit: change the table and run the script (ROADMAP §10.5).

//! The syscall table (ROADMAP §10.5, C-SYSTABLE), generated from
//! `syscalls.toml`: one [`Row`] per syscall, the [`Handlers`] each
//! syscall calls, and per architecture the numbers and the typed
//! `dispatch` (SYSCALL.md §1, §3).

use crate::kerror::KError;

/// What a syscall handler returns: the result, or the error dispatch
/// returns as `-errno` (SYSCALL.md §2).
pub type SysResult = Result<usize, KError>;

/// One syscall's row of the generated table (`syscalls.toml`, ROADMAP §10.5).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Row {
    pub sys: Sys,
    pub name: &'static str,
    /// The arguments, in canonical (x86_64) register order; the arity is
    /// their count.
    pub args: &'static [Arg],
    /// The number on each architecture, `None` where Linux has none.
    pub x86_64: Option<u32>,
    pub aarch64: Option<u32>,
}

impl Row {
    /// The number of arguments.
    pub const fn arity(&self) -> usize {
        self.args.len()
    }
}

/// One argument of a [`Row`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Arg {
    pub name: &'static str,
    pub ty: CType,
    /// How the handler copies through a pointer; `None` for an integer.
    pub ptr: Option<Ptr>,
}

/// An argument's C type in Linux's prototype. Dispatch cuts each register
/// to it: `int` and `pid_t` to `i32`, `unsigned int` to `u32`, `long` and
/// `off_t` to `i64`, `unsigned long` and a pointer to `u64`, `size_t` to
/// `usize`, `umode_t` to `u16` (SYSCALL.md §1).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CType {
    Int,
    UInt,
    Long,
    ULong,
    SizeT,
    OffT,
    PidT,
    UmodeT,
    Ptr,
}

impl CType {
    /// True for the integer types.
    pub const fn is_int(self) -> bool {
        !matches!(self, CType::Ptr)
    }
}

/// A pointer argument's declaration (SYSCALL.md §3).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Ptr {
    pub kind: PtrKind,
    pub dir: Dir,
    /// NULL is valid and copies nothing.
    pub nullable: bool,
    /// Where the handler first copies through it, after which of Linux's
    /// checks.
    pub when: &'static str,
}

/// What a pointer argument points at.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PtrKind {
    /// A buffer whose length is argument `len_from`.
    Buf { len_from: u8 },
    /// A value of `size` bytes.
    Fixed { size: u32 },
    /// A NUL-terminated string.
    CStr,
    /// A NULL-terminated array of C strings.
    StrVec,
    /// A pointer the kernel does not read yet; the row names the ROADMAP
    /// line that reads it.
    Unread,
}

/// Whether the kernel reads or writes through a pointer.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dir {
    In,
    Out,
}

/// How an architecture's entry reads the syscall number (SYSCALL.md §1).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NrRule {
    /// x86_64: `eax` sign-extended, so the high half of `rax` is ignored
    /// and a negative number names no call.
    SignExtendEax,
    /// aarch64: the low 32 bits of `x8`, unsigned.
    Low32,
}

/// An architecture's number table: [`Sys`] by number.
#[derive(Debug)]
pub struct NrTable {
    rule: NrRule,
    slots: &'static [Option<Sys>],
}

impl NrTable {
    pub const fn new(rule: NrRule, slots: &'static [Option<Sys>]) -> NrTable {
        NrTable { rule, slots }
    }

    /// The call `raw`, the full number register, names; `None` for none
    /// (`ENOSYS`).
    pub fn lookup(&self, raw: u64) -> Option<Sys> {
        let n = match self.rule {
            NrRule::SignExtendEax => usize::try_from(raw as u32 as i32).ok()?,
            NrRule::Low32 => raw as u32 as usize,
        };
        self.slots.get(n).copied().flatten()
    }

    /// The table, indexed by number.
    pub const fn slots(&self) -> &'static [Option<Sys>] {
        self.slots
    }
}

/// One syscall, whatever its number on each architecture.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Sys {
    /// `read`.
    Read,
    /// `write`.
    Write,
    /// `open`.
    Open,
    /// `close`.
    Close,
    /// `fstat`.
    Fstat,
    /// `lseek`.
    Lseek,
    /// `mmap`.
    Mmap,
    /// `munmap`.
    Munmap,
    /// `brk`.
    Brk,
    /// `sched_yield`.
    SchedYield,
    /// `dup`.
    Dup,
    /// `dup2`.
    Dup2,
    /// `getpid`.
    Getpid,
    /// `fork`.
    Fork,
    /// `execve`.
    Execve,
    /// `exit`.
    Exit,
    /// `wait4`.
    Wait4,
    /// `kill`.
    Kill,
    /// `fcntl`.
    Fcntl,
    /// `getppid`.
    Getppid,
    /// `getdents64`.
    Getdents64,
    /// `psinfo`.
    Psinfo,
}

impl Sys {
    /// Every syscall, in table order.
    pub const ALL: [Sys; 22] = [
        Sys::Read,
        Sys::Write,
        Sys::Open,
        Sys::Close,
        Sys::Fstat,
        Sys::Lseek,
        Sys::Mmap,
        Sys::Munmap,
        Sys::Brk,
        Sys::SchedYield,
        Sys::Dup,
        Sys::Dup2,
        Sys::Getpid,
        Sys::Fork,
        Sys::Execve,
        Sys::Exit,
        Sys::Wait4,
        Sys::Kill,
        Sys::Fcntl,
        Sys::Getppid,
        Sys::Getdents64,
        Sys::Psinfo,
    ];

    /// This syscall's row.
    pub const fn row(self) -> &'static Row {
        &ROWS[self as usize]
    }
}

/// The rows, in [`Sys`] order.
pub static ROWS: [Row; 22] = [
    Row {
        sys: Sys::Read,
        name: "read",
        args: &[
            Arg {
                name: "fd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "buf",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::Buf { len_from: 2 },
                    dir: Dir::Out,
                    nullable: false,
                    when: "after the `fd` lookup",
                }),
            },
            Arg {
                name: "count",
                ty: CType::SizeT,
                ptr: None,
            },
        ],
        x86_64: Some(0),
        aarch64: Some(63),
    },
    Row {
        sys: Sys::Write,
        name: "write",
        args: &[
            Arg {
                name: "fd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "buf",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::Buf { len_from: 2 },
                    dir: Dir::In,
                    nullable: false,
                    when: "after the `fd` lookup",
                }),
            },
            Arg {
                name: "count",
                ty: CType::SizeT,
                ptr: None,
            },
        ],
        x86_64: Some(1),
        aarch64: Some(64),
    },
    Row {
        sys: Sys::Open,
        name: "open",
        args: &[
            Arg {
                name: "pathname",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::CStr,
                    dir: Dir::In,
                    nullable: false,
                    when: "before anything else",
                }),
            },
            Arg {
                name: "flags",
                ty: CType::Int,
                ptr: None,
            },
            Arg {
                name: "mode",
                ty: CType::UmodeT,
                ptr: None,
            },
        ],
        x86_64: Some(2),
        aarch64: None,
    },
    Row {
        sys: Sys::Close,
        name: "close",
        args: &[Arg {
            name: "fd",
            ty: CType::UInt,
            ptr: None,
        }],
        x86_64: Some(3),
        aarch64: Some(57),
    },
    Row {
        sys: Sys::Fstat,
        name: "fstat",
        args: &[
            Arg {
                name: "fd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "statbuf",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::Fixed { size: 144 },
                    dir: Dir::Out,
                    nullable: false,
                    when: "after the `fd` lookup",
                }),
            },
        ],
        x86_64: Some(5),
        aarch64: Some(80),
    },
    Row {
        sys: Sys::Lseek,
        name: "lseek",
        args: &[
            Arg {
                name: "fd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "offset",
                ty: CType::OffT,
                ptr: None,
            },
            Arg {
                name: "whence",
                ty: CType::UInt,
                ptr: None,
            },
        ],
        x86_64: Some(8),
        aarch64: Some(62),
    },
    Row {
        sys: Sys::Mmap,
        name: "mmap",
        args: &[
            Arg {
                name: "addr",
                ty: CType::ULong,
                ptr: None,
            },
            Arg {
                name: "length",
                ty: CType::ULong,
                ptr: None,
            },
            Arg {
                name: "prot",
                ty: CType::ULong,
                ptr: None,
            },
            Arg {
                name: "flags",
                ty: CType::ULong,
                ptr: None,
            },
            Arg {
                name: "fd",
                ty: CType::ULong,
                ptr: None,
            },
            Arg {
                name: "offset",
                ty: CType::ULong,
                ptr: None,
            },
        ],
        x86_64: Some(9),
        aarch64: Some(222),
    },
    Row {
        sys: Sys::Munmap,
        name: "munmap",
        args: &[
            Arg {
                name: "addr",
                ty: CType::ULong,
                ptr: None,
            },
            Arg {
                name: "length",
                ty: CType::SizeT,
                ptr: None,
            },
        ],
        x86_64: Some(11),
        aarch64: Some(215),
    },
    Row {
        sys: Sys::Brk,
        name: "brk",
        args: &[Arg {
            name: "addr",
            ty: CType::ULong,
            ptr: None,
        }],
        x86_64: Some(12),
        aarch64: Some(214),
    },
    Row {
        sys: Sys::SchedYield,
        name: "sched_yield",
        args: &[],
        x86_64: Some(24),
        aarch64: Some(124),
    },
    Row {
        sys: Sys::Dup,
        name: "dup",
        args: &[Arg {
            name: "oldfd",
            ty: CType::UInt,
            ptr: None,
        }],
        x86_64: Some(32),
        aarch64: Some(23),
    },
    Row {
        sys: Sys::Dup2,
        name: "dup2",
        args: &[
            Arg {
                name: "oldfd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "newfd",
                ty: CType::UInt,
                ptr: None,
            },
        ],
        x86_64: Some(33),
        aarch64: None,
    },
    Row {
        sys: Sys::Getpid,
        name: "getpid",
        args: &[],
        x86_64: Some(39),
        aarch64: Some(172),
    },
    Row {
        sys: Sys::Fork,
        name: "fork",
        args: &[],
        x86_64: Some(57),
        aarch64: None,
    },
    Row {
        sys: Sys::Execve,
        name: "execve",
        args: &[
            Arg {
                name: "pathname",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::CStr,
                    dir: Dir::In,
                    nullable: false,
                    when: "before anything else",
                }),
            },
            Arg {
                name: "argv",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::StrVec,
                    dir: Dir::In,
                    nullable: true,
                    when: "after `pathname`",
                }),
            },
            Arg {
                name: "envp",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::StrVec,
                    dir: Dir::In,
                    nullable: true,
                    when: "after `argv`",
                }),
            },
        ],
        x86_64: Some(59),
        aarch64: Some(221),
    },
    Row {
        sys: Sys::Exit,
        name: "exit",
        args: &[Arg {
            name: "status",
            ty: CType::Int,
            ptr: None,
        }],
        x86_64: Some(60),
        aarch64: Some(93),
    },
    Row {
        sys: Sys::Wait4,
        name: "wait4",
        args: &[
            Arg {
                name: "pid",
                ty: CType::PidT,
                ptr: None,
            },
            Arg {
                name: "wstatus",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::Fixed { size: 4 },
                    dir: Dir::Out,
                    nullable: true,
                    when: "after a child is reaped",
                }),
            },
            Arg {
                name: "options",
                ty: CType::Int,
                ptr: None,
            },
            Arg {
                name: "rusage",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::Unread,
                    dir: Dir::In,
                    nullable: false,
                    when: "not read (ROADMAP §13.7)",
                }),
            },
        ],
        x86_64: Some(61),
        aarch64: Some(260),
    },
    Row {
        sys: Sys::Kill,
        name: "kill",
        args: &[
            Arg {
                name: "pid",
                ty: CType::PidT,
                ptr: None,
            },
            Arg {
                name: "sig",
                ty: CType::Int,
                ptr: None,
            },
        ],
        x86_64: Some(62),
        aarch64: Some(129),
    },
    Row {
        sys: Sys::Fcntl,
        name: "fcntl",
        args: &[
            Arg {
                name: "fd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "cmd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "arg",
                ty: CType::ULong,
                ptr: None,
            },
        ],
        x86_64: Some(72),
        aarch64: Some(25),
    },
    Row {
        sys: Sys::Getppid,
        name: "getppid",
        args: &[],
        x86_64: Some(110),
        aarch64: Some(173),
    },
    Row {
        sys: Sys::Getdents64,
        name: "getdents64",
        args: &[
            Arg {
                name: "fd",
                ty: CType::UInt,
                ptr: None,
            },
            Arg {
                name: "dirent",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::Buf { len_from: 2 },
                    dir: Dir::Out,
                    nullable: false,
                    when: "after the `fd` lookup and the first record's fit",
                }),
            },
            Arg {
                name: "count",
                ty: CType::UInt,
                ptr: None,
            },
        ],
        x86_64: Some(217),
        aarch64: Some(61),
    },
    Row {
        sys: Sys::Psinfo,
        name: "psinfo",
        args: &[
            Arg {
                name: "buf",
                ty: CType::Ptr,
                ptr: Some(Ptr {
                    kind: PtrKind::Buf { len_from: 1 },
                    dir: Dir::Out,
                    nullable: false,
                    when: "before anything else",
                }),
            },
            Arg {
                name: "len",
                ty: CType::SizeT,
                ptr: None,
            },
        ],
        x86_64: Some(500),
        aarch64: None,
    },
];

/// The handlers: one method per row, each argument in its C type
/// (SYSCALL.md §1). A new row fails to compile until its handler exists.
pub trait Handlers {
    /// `read`.
    fn read(&mut self, fd: u32, buf: u64, count: usize) -> SysResult;
    /// `write`.
    fn write(&mut self, fd: u32, buf: u64, count: usize) -> SysResult;
    /// `open`.
    fn open(&mut self, pathname: u64, flags: i32, mode: u16) -> SysResult;
    /// `close`.
    fn close(&mut self, fd: u32) -> SysResult;
    /// `fstat`.
    fn fstat(&mut self, fd: u32, statbuf: u64) -> SysResult;
    /// `lseek`.
    fn lseek(&mut self, fd: u32, offset: i64, whence: u32) -> SysResult;
    /// `mmap`.
    fn mmap(
        &mut self,
        addr: u64,
        length: u64,
        prot: u64,
        flags: u64,
        fd: u64,
        offset: u64,
    ) -> SysResult;
    /// `munmap`.
    fn munmap(&mut self, addr: u64, length: usize) -> SysResult;
    /// `brk`.
    fn brk(&mut self, addr: u64) -> SysResult;
    /// `sched_yield`.
    fn sched_yield(&mut self) -> SysResult;
    /// `dup`.
    fn dup(&mut self, oldfd: u32) -> SysResult;
    /// `dup2`.
    fn dup2(&mut self, oldfd: u32, newfd: u32) -> SysResult;
    /// `getpid`.
    fn getpid(&mut self) -> SysResult;
    /// `fork`.
    fn fork(&mut self) -> SysResult;
    /// `execve`.
    fn execve(&mut self, pathname: u64, argv: u64, envp: u64) -> SysResult;
    /// `exit`.
    fn exit(&mut self, status: i32) -> SysResult;
    /// `wait4`.
    fn wait4(&mut self, pid: i32, wstatus: u64, options: i32, rusage: u64) -> SysResult;
    /// `kill`.
    fn kill(&mut self, pid: i32, sig: i32) -> SysResult;
    /// `fcntl`.
    fn fcntl(&mut self, fd: u32, cmd: u32, arg: u64) -> SysResult;
    /// `getppid`.
    fn getppid(&mut self) -> SysResult;
    /// `getdents64`.
    fn getdents64(&mut self, fd: u32, dirent: u64, count: u32) -> SysResult;
    /// `psinfo`.
    fn psinfo(&mut self, buf: u64, len: usize) -> SysResult;
}

/// x86_64: the number is `eax` sign-extended (SYSCALL.md §1).
pub mod x86_64 {
    use super::{Handlers, NrRule, NrTable, Sys, SysResult};
    use crate::kerror::KError;

    /// The x86_64 numbers.
    pub mod nr {
        /// `read`.
        pub const SYS_READ: u64 = 0;
        /// `write`.
        pub const SYS_WRITE: u64 = 1;
        /// `open`.
        pub const SYS_OPEN: u64 = 2;
        /// `close`.
        pub const SYS_CLOSE: u64 = 3;
        /// `fstat`.
        pub const SYS_FSTAT: u64 = 5;
        /// `lseek`.
        pub const SYS_LSEEK: u64 = 8;
        /// `mmap`.
        pub const SYS_MMAP: u64 = 9;
        /// `munmap`.
        pub const SYS_MUNMAP: u64 = 11;
        /// `brk`.
        pub const SYS_BRK: u64 = 12;
        /// `sched_yield`.
        pub const SYS_SCHED_YIELD: u64 = 24;
        /// `dup`.
        pub const SYS_DUP: u64 = 32;
        /// `dup2`.
        pub const SYS_DUP2: u64 = 33;
        /// `getpid`.
        pub const SYS_GETPID: u64 = 39;
        /// `fork`.
        pub const SYS_FORK: u64 = 57;
        /// `execve`.
        pub const SYS_EXECVE: u64 = 59;
        /// `exit`.
        pub const SYS_EXIT: u64 = 60;
        /// `wait4`.
        pub const SYS_WAIT4: u64 = 61;
        /// `kill`.
        pub const SYS_KILL: u64 = 62;
        /// `fcntl`.
        pub const SYS_FCNTL: u64 = 72;
        /// `getppid`.
        pub const SYS_GETPPID: u64 = 110;
        /// `getdents64`.
        pub const SYS_GETDENTS64: u64 = 217;
        /// `psinfo`.
        pub const SYS_PSINFO: u64 = 500;
    }

    const SLOTS: [Option<Sys>; 501] = {
        let mut t = [None; 501];
        t[nr::SYS_READ as usize] = Some(Sys::Read);
        t[nr::SYS_WRITE as usize] = Some(Sys::Write);
        t[nr::SYS_OPEN as usize] = Some(Sys::Open);
        t[nr::SYS_CLOSE as usize] = Some(Sys::Close);
        t[nr::SYS_FSTAT as usize] = Some(Sys::Fstat);
        t[nr::SYS_LSEEK as usize] = Some(Sys::Lseek);
        t[nr::SYS_MMAP as usize] = Some(Sys::Mmap);
        t[nr::SYS_MUNMAP as usize] = Some(Sys::Munmap);
        t[nr::SYS_BRK as usize] = Some(Sys::Brk);
        t[nr::SYS_SCHED_YIELD as usize] = Some(Sys::SchedYield);
        t[nr::SYS_DUP as usize] = Some(Sys::Dup);
        t[nr::SYS_DUP2 as usize] = Some(Sys::Dup2);
        t[nr::SYS_GETPID as usize] = Some(Sys::Getpid);
        t[nr::SYS_FORK as usize] = Some(Sys::Fork);
        t[nr::SYS_EXECVE as usize] = Some(Sys::Execve);
        t[nr::SYS_EXIT as usize] = Some(Sys::Exit);
        t[nr::SYS_WAIT4 as usize] = Some(Sys::Wait4);
        t[nr::SYS_KILL as usize] = Some(Sys::Kill);
        t[nr::SYS_FCNTL as usize] = Some(Sys::Fcntl);
        t[nr::SYS_GETPPID as usize] = Some(Sys::Getppid);
        t[nr::SYS_GETDENTS64 as usize] = Some(Sys::Getdents64);
        t[nr::SYS_PSINFO as usize] = Some(Sys::Psinfo);
        t
    };

    /// The table dispatch indexes by number.
    pub static TABLE: NrTable = NrTable::new(NrRule::SignExtendEax, &SLOTS);

    /// Call `sys`'s handler, each register cut to its argument's C type.
    pub fn call<H: Handlers + ?Sized>(h: &mut H, sys: Sys, regs: &[u64; 6]) -> SysResult {
        match sys {
            Sys::Read => h.read(regs[0] as u32, regs[1], regs[2] as usize),
            Sys::Write => h.write(regs[0] as u32, regs[1], regs[2] as usize),
            Sys::Open => h.open(regs[0], regs[1] as i32, regs[2] as u16),
            Sys::Close => h.close(regs[0] as u32),
            Sys::Fstat => h.fstat(regs[0] as u32, regs[1]),
            Sys::Lseek => h.lseek(regs[0] as u32, regs[1] as i64, regs[2] as u32),
            Sys::Mmap => h.mmap(regs[0], regs[1], regs[2], regs[3], regs[4], regs[5]),
            Sys::Munmap => h.munmap(regs[0], regs[1] as usize),
            Sys::Brk => h.brk(regs[0]),
            Sys::SchedYield => h.sched_yield(),
            Sys::Dup => h.dup(regs[0] as u32),
            Sys::Dup2 => h.dup2(regs[0] as u32, regs[1] as u32),
            Sys::Getpid => h.getpid(),
            Sys::Fork => h.fork(),
            Sys::Execve => h.execve(regs[0], regs[1], regs[2]),
            Sys::Exit => h.exit(regs[0] as i32),
            Sys::Wait4 => h.wait4(regs[0] as i32, regs[1], regs[2] as i32, regs[3]),
            Sys::Kill => h.kill(regs[0] as i32, regs[1] as i32),
            Sys::Fcntl => h.fcntl(regs[0] as u32, regs[1] as u32, regs[2]),
            Sys::Getppid => h.getppid(),
            Sys::Getdents64 => h.getdents64(regs[0] as u32, regs[1], regs[2] as u32),
            Sys::Psinfo => h.psinfo(regs[0], regs[1] as usize),
        }
    }

    /// Look `raw_nr` up as Linux reads it and call its handler; a
    /// number that names no row is `ENOSYS`.
    pub fn dispatch<H: Handlers + ?Sized>(h: &mut H, raw_nr: u64, regs: &[u64; 6]) -> SysResult {
        match TABLE.lookup(raw_nr) {
            Some(sys) => call(h, sys, regs),
            None => Err(KError::ENOSYS),
        }
    }
}

/// aarch64: the number is the low 32 bits of `x8`, unsigned (ROADMAP §11.6).
pub mod aarch64 {
    use super::{Handlers, NrRule, NrTable, Sys, SysResult};
    use crate::kerror::KError;

    /// The aarch64 numbers.
    pub mod nr {
        /// `read`.
        pub const SYS_READ: u64 = 63;
        /// `write`.
        pub const SYS_WRITE: u64 = 64;
        /// `close`.
        pub const SYS_CLOSE: u64 = 57;
        /// `fstat`.
        pub const SYS_FSTAT: u64 = 80;
        /// `lseek`.
        pub const SYS_LSEEK: u64 = 62;
        /// `mmap`.
        pub const SYS_MMAP: u64 = 222;
        /// `munmap`.
        pub const SYS_MUNMAP: u64 = 215;
        /// `brk`.
        pub const SYS_BRK: u64 = 214;
        /// `sched_yield`.
        pub const SYS_SCHED_YIELD: u64 = 124;
        /// `dup`.
        pub const SYS_DUP: u64 = 23;
        /// `getpid`.
        pub const SYS_GETPID: u64 = 172;
        /// `execve`.
        pub const SYS_EXECVE: u64 = 221;
        /// `exit`.
        pub const SYS_EXIT: u64 = 93;
        /// `wait4`.
        pub const SYS_WAIT4: u64 = 260;
        /// `kill`.
        pub const SYS_KILL: u64 = 129;
        /// `fcntl`.
        pub const SYS_FCNTL: u64 = 25;
        /// `getppid`.
        pub const SYS_GETPPID: u64 = 173;
        /// `getdents64`.
        pub const SYS_GETDENTS64: u64 = 61;
    }

    const SLOTS: [Option<Sys>; 261] = {
        let mut t = [None; 261];
        t[nr::SYS_READ as usize] = Some(Sys::Read);
        t[nr::SYS_WRITE as usize] = Some(Sys::Write);
        t[nr::SYS_CLOSE as usize] = Some(Sys::Close);
        t[nr::SYS_FSTAT as usize] = Some(Sys::Fstat);
        t[nr::SYS_LSEEK as usize] = Some(Sys::Lseek);
        t[nr::SYS_MMAP as usize] = Some(Sys::Mmap);
        t[nr::SYS_MUNMAP as usize] = Some(Sys::Munmap);
        t[nr::SYS_BRK as usize] = Some(Sys::Brk);
        t[nr::SYS_SCHED_YIELD as usize] = Some(Sys::SchedYield);
        t[nr::SYS_DUP as usize] = Some(Sys::Dup);
        t[nr::SYS_GETPID as usize] = Some(Sys::Getpid);
        t[nr::SYS_EXECVE as usize] = Some(Sys::Execve);
        t[nr::SYS_EXIT as usize] = Some(Sys::Exit);
        t[nr::SYS_WAIT4 as usize] = Some(Sys::Wait4);
        t[nr::SYS_KILL as usize] = Some(Sys::Kill);
        t[nr::SYS_FCNTL as usize] = Some(Sys::Fcntl);
        t[nr::SYS_GETPPID as usize] = Some(Sys::Getppid);
        t[nr::SYS_GETDENTS64 as usize] = Some(Sys::Getdents64);
        t
    };

    /// The table dispatch indexes by number.
    pub static TABLE: NrTable = NrTable::new(NrRule::Low32, &SLOTS);

    /// Call `sys`'s handler, each register cut to its argument's C type.
    pub fn call<H: Handlers + ?Sized>(h: &mut H, sys: Sys, regs: &[u64; 6]) -> SysResult {
        match sys {
            Sys::Read => h.read(regs[0] as u32, regs[1], regs[2] as usize),
            Sys::Write => h.write(regs[0] as u32, regs[1], regs[2] as usize),
            Sys::Close => h.close(regs[0] as u32),
            Sys::Fstat => h.fstat(regs[0] as u32, regs[1]),
            Sys::Lseek => h.lseek(regs[0] as u32, regs[1] as i64, regs[2] as u32),
            Sys::Mmap => h.mmap(regs[0], regs[1], regs[2], regs[3], regs[4], regs[5]),
            Sys::Munmap => h.munmap(regs[0], regs[1] as usize),
            Sys::Brk => h.brk(regs[0]),
            Sys::SchedYield => h.sched_yield(),
            Sys::Dup => h.dup(regs[0] as u32),
            Sys::Getpid => h.getpid(),
            Sys::Execve => h.execve(regs[0], regs[1], regs[2]),
            Sys::Exit => h.exit(regs[0] as i32),
            Sys::Wait4 => h.wait4(regs[0] as i32, regs[1], regs[2] as i32, regs[3]),
            Sys::Kill => h.kill(regs[0] as i32, regs[1] as i32),
            Sys::Fcntl => h.fcntl(regs[0] as u32, regs[1] as u32, regs[2]),
            Sys::Getppid => h.getppid(),
            Sys::Getdents64 => h.getdents64(regs[0] as u32, regs[1], regs[2] as u32),
            Sys::Open | Sys::Dup2 | Sys::Fork | Sys::Psinfo => Err(KError::ENOSYS),
        }
    }

    /// Look `raw_nr` up as Linux reads it and call its handler; a
    /// number that names no row is `ENOSYS`.
    pub fn dispatch<H: Handlers + ?Sized>(h: &mut H, raw_nr: u64, regs: &[u64; 6]) -> SysResult {
        match TABLE.lookup(raw_nr) {
            Some(sys) => call(h, sys, regs),
            None => Err(KError::ENOSYS),
        }
    }
}

/// One argument as a handler received it (host tests).
#[cfg(test)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Val {
    I32(i32),
    U32(u32),
    I64(i64),
    U64(u64),
    Usize(usize),
    U16(u16),
    Ptr(u64),
}

/// A [`Handlers`] that keeps the last call's typed arguments (host tests).
#[cfg(test)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Recorder {
    /// The last call.
    pub sys: Option<Sys>,
    /// Its arguments, in canonical order.
    pub args: [Option<Val>; 6],
}

#[cfg(test)]
impl Recorder {
    fn record(&mut self, sys: Sys, vals: &[Val]) -> SysResult {
        let mut args = [None; 6];
        for (slot, v) in args.iter_mut().zip(vals) {
            *slot = Some(*v);
        }
        *self = Recorder {
            sys: Some(sys),
            args,
        };
        Ok(0)
    }
}

#[cfg(test)]
impl Handlers for Recorder {
    fn read(&mut self, fd: u32, buf: u64, count: usize) -> SysResult {
        self.record(Sys::Read, &[Val::U32(fd), Val::Ptr(buf), Val::Usize(count)])
    }

    fn write(&mut self, fd: u32, buf: u64, count: usize) -> SysResult {
        self.record(
            Sys::Write,
            &[Val::U32(fd), Val::Ptr(buf), Val::Usize(count)],
        )
    }

    fn open(&mut self, pathname: u64, flags: i32, mode: u16) -> SysResult {
        self.record(
            Sys::Open,
            &[Val::Ptr(pathname), Val::I32(flags), Val::U16(mode)],
        )
    }

    fn close(&mut self, fd: u32) -> SysResult {
        self.record(Sys::Close, &[Val::U32(fd)])
    }

    fn fstat(&mut self, fd: u32, statbuf: u64) -> SysResult {
        self.record(Sys::Fstat, &[Val::U32(fd), Val::Ptr(statbuf)])
    }

    fn lseek(&mut self, fd: u32, offset: i64, whence: u32) -> SysResult {
        self.record(
            Sys::Lseek,
            &[Val::U32(fd), Val::I64(offset), Val::U32(whence)],
        )
    }

    fn mmap(
        &mut self,
        addr: u64,
        length: u64,
        prot: u64,
        flags: u64,
        fd: u64,
        offset: u64,
    ) -> SysResult {
        self.record(
            Sys::Mmap,
            &[
                Val::U64(addr),
                Val::U64(length),
                Val::U64(prot),
                Val::U64(flags),
                Val::U64(fd),
                Val::U64(offset),
            ],
        )
    }

    fn munmap(&mut self, addr: u64, length: usize) -> SysResult {
        self.record(Sys::Munmap, &[Val::U64(addr), Val::Usize(length)])
    }

    fn brk(&mut self, addr: u64) -> SysResult {
        self.record(Sys::Brk, &[Val::U64(addr)])
    }

    fn sched_yield(&mut self) -> SysResult {
        self.record(Sys::SchedYield, &[])
    }

    fn dup(&mut self, oldfd: u32) -> SysResult {
        self.record(Sys::Dup, &[Val::U32(oldfd)])
    }

    fn dup2(&mut self, oldfd: u32, newfd: u32) -> SysResult {
        self.record(Sys::Dup2, &[Val::U32(oldfd), Val::U32(newfd)])
    }

    fn getpid(&mut self) -> SysResult {
        self.record(Sys::Getpid, &[])
    }

    fn fork(&mut self) -> SysResult {
        self.record(Sys::Fork, &[])
    }

    fn execve(&mut self, pathname: u64, argv: u64, envp: u64) -> SysResult {
        self.record(
            Sys::Execve,
            &[Val::Ptr(pathname), Val::Ptr(argv), Val::Ptr(envp)],
        )
    }

    fn exit(&mut self, status: i32) -> SysResult {
        self.record(Sys::Exit, &[Val::I32(status)])
    }

    fn wait4(&mut self, pid: i32, wstatus: u64, options: i32, rusage: u64) -> SysResult {
        self.record(
            Sys::Wait4,
            &[
                Val::I32(pid),
                Val::Ptr(wstatus),
                Val::I32(options),
                Val::Ptr(rusage),
            ],
        )
    }

    fn kill(&mut self, pid: i32, sig: i32) -> SysResult {
        self.record(Sys::Kill, &[Val::I32(pid), Val::I32(sig)])
    }

    fn fcntl(&mut self, fd: u32, cmd: u32, arg: u64) -> SysResult {
        self.record(Sys::Fcntl, &[Val::U32(fd), Val::U32(cmd), Val::U64(arg)])
    }

    fn getppid(&mut self) -> SysResult {
        self.record(Sys::Getppid, &[])
    }

    fn getdents64(&mut self, fd: u32, dirent: u64, count: u32) -> SysResult {
        self.record(
            Sys::Getdents64,
            &[Val::U32(fd), Val::Ptr(dirent), Val::U32(count)],
        )
    }

    fn psinfo(&mut self, buf: u64, len: usize) -> SysResult {
        self.record(Sys::Psinfo, &[Val::Ptr(buf), Val::Usize(len)])
    }
}
