"""Host tests for scripts/check_errors.py (ROADMAP §10.4, E2, C-KERROR)."""

from __future__ import annotations

import contextlib
import io
import unittest

from scripts import check_errors
from scripts.check_errors import KERROR, check

GOOD_TYPE = """\
pub enum DiskError {
    Io,
    Gone,
}

impl From<DiskError> for crate::kerror::KError {
    fn from(e: DiskError) -> Self {
        match e {
            DiskError::Io => Self::Io,
            DiskError::Gone => Self::NoDev,
        }
    }
}
"""

EXTRA = """\
pub struct Dead;
impl From<Dead> for KError {
    fn from(_: Dead) -> Self {
        Self::NoDev
    }
}
pub struct Fault;
impl From<Fault> for KError {
    fn from(_: Fault) -> Self {
        Self::Fault
    }
}
pub struct IpiRefused;
impl From<IpiRefused> for vibeos::kerror::KError {
    fn from(_: IpiRefused) -> Self {
        Self::Io
    }
}
"""


def run(*files: tuple[str, str]) -> list[str]:
    return check([("crates/core/src/extra.rs", EXTRA), *files])


class RuleA(unittest.TestCase):
    def test_errno_const_fails(self) -> None:
        got = run(("src/a.rs", "pub const EINVAL: i32 = 22;\n"))
        self.assertEqual(len(got), 1)
        self.assertIn("src/a.rs:1: const EINVAL is named for a Linux errno", got[0])

    def test_associated_const_fails(self) -> None:
        text = "impl UserMemError {\n    pub const EFAULT: i32 = 14;\n}\n"
        got = run(("crates/core/src/b.rs", text))
        self.assertEqual(len(got), 1)
        self.assertIn("crates/core/src/b.rs:2: const EFAULT", got[0])

    def test_every_tree_is_read(self) -> None:
        for path in ("user/src/c.rs", "tests/hostlib/src/bin/d.rs"):
            with self.subTest(path=path):
                self.assertEqual(len(run((path, "const ENOSPC: u32 = 28;\n"))), 1)

    def test_kerror_and_generated_files_pass(self) -> None:
        gen = (
            "// @generated by scripts/gen_syscalls.py from crates/core/src/kerror.rs.\n"
            "impl Errno {\n    pub const EBADF: Errno = Errno(9);\n}\n"
        )
        self.assertEqual(run((KERROR, "const EPERM: i32 = 1;\n"), ("user/src/errno.rs", gen)), [])

    def test_non_errno_names_and_comments_pass(self) -> None:
        text = (
            "const EOF: u8 = 0;\nconst EINVAL_COUNT: u32 = 1;\nconst NBD_EIO: u32 = 5;\n"
            "// const EINVAL: i32 = 22;\n"
        )
        self.assertEqual(run(("src/e.rs", text)), [])


class RuleB(unittest.TestCase):
    def test_error_type_without_from_fails(self) -> None:
        got = run(("crates/core/src/f.rs", "#[derive(Debug)]\npub enum PartError {\n    Bad,\n}\n"))
        self.assertEqual(
            got, ["crates/core/src/f.rs:2: PartError has no `impl From<PartError> for KError`"]
        )

    def test_error_type_with_from_passes(self) -> None:
        self.assertEqual(run(("crates/core/src/g.rs", GOOD_TYPE)), [])

    def test_from_in_another_file_passes(self) -> None:
        a = "pub(crate) struct LoadError;\n"
        b = (
            "impl From<crate::user_init::LoadError> for KError {\n"
            "    fn from(_: LoadError) -> Self {\n        Self::NoExec\n    }\n}\n"
        )
        self.assertEqual(run(("src/proc/user_init.rs", a), ("src/proc/other.rs", b)), [])

    def test_extra_error_without_from_fails(self) -> None:
        got = check([("crates/core/src/sync/mod.rs", "pub struct Dead;\n")])
        self.assertIn(
            "crates/core/src/sync/mod.rs:1: Dead has no `impl From<Dead> for KError`", got
        )

    def test_extra_error_that_is_gone_fails(self) -> None:
        got = check([])
        self.assertEqual(len(got), len(check_errors.EXTRA_ERRORS))
        self.assertIn("EXTRA_ERRORS names Dead", got[0])

    def test_alias_test_code_and_other_trees_do_not_count(self) -> None:
        alias = "pub type FatError = super::FsError;\n"
        in_test = "fn f() {}\n\n#[cfg(test)]\nmod tests {\n    enum FakeError { A }\n}\n"
        self.assertEqual(
            run(
                ("crates/core/src/fs/fat/mod.rs", alias),
                ("crates/core/src/h.rs", in_test),
                ("crates/core/src/fs/tests.rs", "enum TestError { A }\n"),
                ("src/proc/ktest/x.rs", "pub(crate) enum ReaderError { A }\n"),
                ("src/fs/ktest.rs", "enum KtError { A }\n"),
                ("user/src/i.rs", "pub enum UserError { A }\n"),
            ),
            [],
        )


class RuleC(unittest.TestCase):
    def test_wildcard_arm_fails(self) -> None:
        text = GOOD_TYPE.replace("DiskError::Gone => Self::NoDev,", "_ => Self::NoDev,")
        got = run(("crates/core/src/j.rs", text))
        self.assertEqual(len(got), 1)
        self.assertIn(
            "crates/core/src/j.rs:6: impl From<DiskError> for KError has a `_ =>` arm", got[0]
        )

    def test_or_wildcard_and_guard_fail(self) -> None:
        for arm in ("DiskError::Io | _ => Self::Io,", "_ if true => Self::Io,"):
            with self.subTest(arm=arm):
                text = GOOD_TYPE.replace("DiskError::Io => Self::Io,", arm)
                self.assertEqual(len(run(("crates/core/src/k.rs", text))), 1)

    def test_wildcard_inside_a_pattern_passes(self) -> None:
        text = GOOD_TYPE.replace(
            "pub enum DiskError {\n    Io,", "pub enum DiskError {\n    Io(u8),"
        ).replace("DiskError::Io => Self::Io,", "DiskError::Io(_) => Self::Io,")
        self.assertEqual(run(("crates/core/src/l.rs", text)), [])

    def test_wildcard_in_another_impl_passes(self) -> None:
        other = (
            "impl Foo {\n    fn f(x: u8) -> u8 {\n"
            "        match x {\n            _ => 0,\n        }\n    }\n}\n"
        )
        self.assertEqual(run(("crates/core/src/m.rs", GOOD_TYPE + other)), [])


class Tree(unittest.TestCase):
    def test_real_tree_passes(self) -> None:
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            self.assertEqual(check_errors.main([]), 0)
        self.assertIn("check_errors: ok", out.getvalue())


if __name__ == "__main__":
    unittest.main()
