"""Unit tests for the marker registry and the lists the harness builds (ROADMAP §10.2).

`TestContractLists` holds each configuration's contract list, the panic
signatures and the unframed and Limine failure lists as `harness.py` built
them at P10-S42's branch point (`BRANCH_POINT`), and finds today's lists
equal to them.

Runs under `python3 -m unittest discover`. Standard-library only.
"""

from __future__ import annotations

import os
import unittest
from typing import Any
from unittest import mock

from tests.harness import frame, harness
from tests.harness.harness import Marker

# (substring, name, and_contains, exactly_before, the side of the frame the
# marker matches on: `Marker.source`, or `frame.source_of` when it is empty).
Entry = tuple[str, str, tuple[str, ...], tuple[str, int] | None, str]

# The `boot_contract_markers` arguments of each configuration. Every argument
# is explicit, and the environment is cleared, so no `VIBEOS_*` reaches them.
CONFIGS: dict[str, dict[str, Any]] = {
    "hpet_smp1": dict(hpet=True, cpu="max", accel="tcg", smp=1),
    "hpet_smp2": dict(hpet=True, cpu="max", accel="tcg", smp=2),
    "hpet_smp4": dict(hpet=True, cpu="max", accel="tcg", smp=4),
    "pit_smp2": dict(hpet=False, cpu="max", accel="tcg", smp=2),
    "kvm_smp2": dict(cpu="max", accel="kvm", smp=2),
    "kvm_notscdl_smp2": dict(cpu="qemu64,-tsc-deadline", accel="kvm", smp=2),
    "gp_smp2": dict(gp=True, cpu="max", accel="tcg", smp=2),
}

# Generated by running the branch-point functions; `halt` is `halt_test_markers()`.
BRANCH_POINT: dict[str, list[Entry]] = {
    'hpet_smp1': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: pmm: ', 'pmm_free_frames', (' free 4KiB frames',), None, 'kernel'),
        ('vibeOS: paging: cr3 ok', 'paging_cr3_ok', (), None, 'kernel'),
        ('vibeOS: paging: mmio uc', 'paging_mmio_uc', (), None, 'kernel'),
        ('vibeOS: heap ok', 'heap_ok', (), None, 'kernel'),
        ('vibeOS: kva: ready', 'kva_ready', (), None, 'kernel'),
        ('vibeOS: gdt ok', 'gdt_ok', (), None, 'kernel'),
        ('vibeOS: pic: remapped', 'pic_remapped', (), None, 'kernel'),
        ('vibeOS: idt ok', 'idt_ok', (), None, 'kernel'),
        ('vibeOS: per_cpu: bsp ready', 'per_cpu_bsp', (), None, 'kernel'),
        ('vibeOS: acpi: xsdt ', 'acpi_xsdt', (' tables',), None, 'kernel'),
        ('vibeOS: time: calibrated hpet ', 'time_calib_hpet', ('/ms',), None, 'kernel'),
        ('vibeOS: time: tsc ', 'time_tsc', ('/ms',), None, 'kernel'),
        ('vibeOS: time: lapic_timer ok (periodic)', 'lapic_timer_ok', (), None, 'kernel'),
        ('vibeOS: sched: cpu0 ready', 'sched_cpu0', (), None, 'kernel'),
        ('vibeOS: irq: enabled', 'irq_enabled', (), None, 'kernel'),
        ('vibeOS: smp: done', 'smp_done', (), ('vibeOS: smp: ap online', 0), 'kernel'),
        ('vibeOS: console ok', 'console_ok', (), None, 'kernel'),
        ('vibeOS: pci: ', 'pci_devices', (' devices',), None, 'kernel'),
        ('vibeOS: block: ram0 ', 'block_ramdisk', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p1 ', 'block_ram0p1', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p2 ', 'block_ram0p2', (' sectors',), None, 'kernel'),
        ('vibeOS: shell ready', 'shell_ready', (), None, 'user'),
    ],
    'hpet_smp2': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: pmm: ', 'pmm_free_frames', (' free 4KiB frames',), None, 'kernel'),
        ('vibeOS: paging: cr3 ok', 'paging_cr3_ok', (), None, 'kernel'),
        ('vibeOS: paging: mmio uc', 'paging_mmio_uc', (), None, 'kernel'),
        ('vibeOS: heap ok', 'heap_ok', (), None, 'kernel'),
        ('vibeOS: kva: ready', 'kva_ready', (), None, 'kernel'),
        ('vibeOS: gdt ok', 'gdt_ok', (), None, 'kernel'),
        ('vibeOS: pic: remapped', 'pic_remapped', (), None, 'kernel'),
        ('vibeOS: idt ok', 'idt_ok', (), None, 'kernel'),
        ('vibeOS: per_cpu: bsp ready', 'per_cpu_bsp', (), None, 'kernel'),
        ('vibeOS: acpi: xsdt ', 'acpi_xsdt', (' tables',), None, 'kernel'),
        ('vibeOS: time: calibrated hpet ', 'time_calib_hpet', ('/ms',), None, 'kernel'),
        ('vibeOS: time: tsc ', 'time_tsc', ('/ms',), None, 'kernel'),
        ('vibeOS: time: lapic_timer ok (periodic)', 'lapic_timer_ok', (), None, 'kernel'),
        ('vibeOS: sched: cpu0 ready', 'sched_cpu0', (), None, 'kernel'),
        ('vibeOS: irq: enabled', 'irq_enabled', (), None, 'kernel'),
        ('vibeOS: sched: cpu1 ready', 'sched_cpu1', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_0', (), None, 'kernel'),
        ('vibeOS: smp: done', 'smp_done', (), ('vibeOS: smp: ap online', 1), 'kernel'),
        ('vibeOS: console ok', 'console_ok', (), None, 'kernel'),
        ('vibeOS: pci: ', 'pci_devices', (' devices',), None, 'kernel'),
        ('vibeOS: block: ram0 ', 'block_ramdisk', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p1 ', 'block_ram0p1', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p2 ', 'block_ram0p2', (' sectors',), None, 'kernel'),
        ('vibeOS: shell ready', 'shell_ready', (), None, 'user'),
    ],
    'hpet_smp4': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: pmm: ', 'pmm_free_frames', (' free 4KiB frames',), None, 'kernel'),
        ('vibeOS: paging: cr3 ok', 'paging_cr3_ok', (), None, 'kernel'),
        ('vibeOS: paging: mmio uc', 'paging_mmio_uc', (), None, 'kernel'),
        ('vibeOS: heap ok', 'heap_ok', (), None, 'kernel'),
        ('vibeOS: kva: ready', 'kva_ready', (), None, 'kernel'),
        ('vibeOS: gdt ok', 'gdt_ok', (), None, 'kernel'),
        ('vibeOS: pic: remapped', 'pic_remapped', (), None, 'kernel'),
        ('vibeOS: idt ok', 'idt_ok', (), None, 'kernel'),
        ('vibeOS: per_cpu: bsp ready', 'per_cpu_bsp', (), None, 'kernel'),
        ('vibeOS: acpi: xsdt ', 'acpi_xsdt', (' tables',), None, 'kernel'),
        ('vibeOS: time: calibrated hpet ', 'time_calib_hpet', ('/ms',), None, 'kernel'),
        ('vibeOS: time: tsc ', 'time_tsc', ('/ms',), None, 'kernel'),
        ('vibeOS: time: lapic_timer ok (periodic)', 'lapic_timer_ok', (), None, 'kernel'),
        ('vibeOS: sched: cpu0 ready', 'sched_cpu0', (), None, 'kernel'),
        ('vibeOS: irq: enabled', 'irq_enabled', (), None, 'kernel'),
        ('vibeOS: sched: cpu1 ready', 'sched_cpu1', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_0', (), None, 'kernel'),
        ('vibeOS: sched: cpu2 ready', 'sched_cpu2', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_1', (), None, 'kernel'),
        ('vibeOS: sched: cpu3 ready', 'sched_cpu3', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_2', (), None, 'kernel'),
        ('vibeOS: smp: done', 'smp_done', (), ('vibeOS: smp: ap online', 3), 'kernel'),
        ('vibeOS: console ok', 'console_ok', (), None, 'kernel'),
        ('vibeOS: pci: ', 'pci_devices', (' devices',), None, 'kernel'),
        ('vibeOS: block: ram0 ', 'block_ramdisk', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p1 ', 'block_ram0p1', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p2 ', 'block_ram0p2', (' sectors',), None, 'kernel'),
        ('vibeOS: shell ready', 'shell_ready', (), None, 'user'),
    ],
    'pit_smp2': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: pmm: ', 'pmm_free_frames', (' free 4KiB frames',), None, 'kernel'),
        ('vibeOS: paging: cr3 ok', 'paging_cr3_ok', (), None, 'kernel'),
        ('vibeOS: paging: mmio uc', 'paging_mmio_uc', (), None, 'kernel'),
        ('vibeOS: heap ok', 'heap_ok', (), None, 'kernel'),
        ('vibeOS: kva: ready', 'kva_ready', (), None, 'kernel'),
        ('vibeOS: gdt ok', 'gdt_ok', (), None, 'kernel'),
        ('vibeOS: pic: remapped', 'pic_remapped', (), None, 'kernel'),
        ('vibeOS: idt ok', 'idt_ok', (), None, 'kernel'),
        ('vibeOS: per_cpu: bsp ready', 'per_cpu_bsp', (), None, 'kernel'),
        ('vibeOS: acpi: xsdt ', 'acpi_xsdt', (' tables',), None, 'kernel'),
        ('vibeOS: time: calibrated pit ', 'time_calib_pit', ('/ms',), None, 'kernel'),
        ('vibeOS: time: tsc ', 'time_tsc', ('/ms',), None, 'kernel'),
        ('vibeOS: time: lapic_timer ok (pit)', 'lapic_timer_ok', (), None, 'kernel'),
        ('vibeOS: sched: cpu0 ready', 'sched_cpu0', (), None, 'kernel'),
        ('vibeOS: irq: enabled', 'irq_enabled', (), None, 'kernel'),
        ('vibeOS: sched: cpu1 ready', 'sched_cpu1', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_0', (), None, 'kernel'),
        ('vibeOS: smp: done', 'smp_done', (), ('vibeOS: smp: ap online', 1), 'kernel'),
        ('vibeOS: console ok', 'console_ok', (), None, 'kernel'),
        ('vibeOS: pci: ', 'pci_devices', (' devices',), None, 'kernel'),
        ('vibeOS: block: ram0 ', 'block_ramdisk', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p1 ', 'block_ram0p1', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p2 ', 'block_ram0p2', (' sectors',), None, 'kernel'),
        ('vibeOS: shell ready', 'shell_ready', (), None, 'user'),
    ],
    'kvm_smp2': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: pmm: ', 'pmm_free_frames', (' free 4KiB frames',), None, 'kernel'),
        ('vibeOS: paging: cr3 ok', 'paging_cr3_ok', (), None, 'kernel'),
        ('vibeOS: paging: mmio uc', 'paging_mmio_uc', (), None, 'kernel'),
        ('vibeOS: heap ok', 'heap_ok', (), None, 'kernel'),
        ('vibeOS: kva: ready', 'kva_ready', (), None, 'kernel'),
        ('vibeOS: gdt ok', 'gdt_ok', (), None, 'kernel'),
        ('vibeOS: pic: remapped', 'pic_remapped', (), None, 'kernel'),
        ('vibeOS: idt ok', 'idt_ok', (), None, 'kernel'),
        ('vibeOS: per_cpu: bsp ready', 'per_cpu_bsp', (), None, 'kernel'),
        ('vibeOS: acpi: xsdt ', 'acpi_xsdt', (' tables',), None, 'kernel'),
        ('vibeOS: time: calibrated hpet ', 'time_calib_hpet', ('/ms',), None, 'kernel'),
        ('vibeOS: time: tsc ', 'time_tsc', ('/ms',), None, 'kernel'),
        ('vibeOS: time: lapic_timer ok (tsc-deadline)', 'lapic_timer_ok', (), None, 'kernel'),
        ('vibeOS: sched: cpu0 ready', 'sched_cpu0', (), None, 'kernel'),
        ('vibeOS: irq: enabled', 'irq_enabled', (), None, 'kernel'),
        ('vibeOS: sched: cpu1 ready', 'sched_cpu1', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_0', (), None, 'kernel'),
        ('vibeOS: smp: done', 'smp_done', (), ('vibeOS: smp: ap online', 1), 'kernel'),
        ('vibeOS: console ok', 'console_ok', (), None, 'kernel'),
        ('vibeOS: pci: ', 'pci_devices', (' devices',), None, 'kernel'),
        ('vibeOS: block: ram0 ', 'block_ramdisk', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p1 ', 'block_ram0p1', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p2 ', 'block_ram0p2', (' sectors',), None, 'kernel'),
        ('vibeOS: shell ready', 'shell_ready', (), None, 'user'),
    ],
    'kvm_notscdl_smp2': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: pmm: ', 'pmm_free_frames', (' free 4KiB frames',), None, 'kernel'),
        ('vibeOS: paging: cr3 ok', 'paging_cr3_ok', (), None, 'kernel'),
        ('vibeOS: paging: mmio uc', 'paging_mmio_uc', (), None, 'kernel'),
        ('vibeOS: heap ok', 'heap_ok', (), None, 'kernel'),
        ('vibeOS: kva: ready', 'kva_ready', (), None, 'kernel'),
        ('vibeOS: gdt ok', 'gdt_ok', (), None, 'kernel'),
        ('vibeOS: pic: remapped', 'pic_remapped', (), None, 'kernel'),
        ('vibeOS: idt ok', 'idt_ok', (), None, 'kernel'),
        ('vibeOS: per_cpu: bsp ready', 'per_cpu_bsp', (), None, 'kernel'),
        ('vibeOS: acpi: xsdt ', 'acpi_xsdt', (' tables',), None, 'kernel'),
        ('vibeOS: time: calibrated hpet ', 'time_calib_hpet', ('/ms',), None, 'kernel'),
        ('vibeOS: time: tsc ', 'time_tsc', ('/ms',), None, 'kernel'),
        ('vibeOS: time: lapic_timer ok (periodic)', 'lapic_timer_ok', (), None, 'kernel'),
        ('vibeOS: sched: cpu0 ready', 'sched_cpu0', (), None, 'kernel'),
        ('vibeOS: irq: enabled', 'irq_enabled', (), None, 'kernel'),
        ('vibeOS: sched: cpu1 ready', 'sched_cpu1', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_0', (), None, 'kernel'),
        ('vibeOS: smp: done', 'smp_done', (), ('vibeOS: smp: ap online', 1), 'kernel'),
        ('vibeOS: console ok', 'console_ok', (), None, 'kernel'),
        ('vibeOS: pci: ', 'pci_devices', (' devices',), None, 'kernel'),
        ('vibeOS: block: ram0 ', 'block_ramdisk', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p1 ', 'block_ram0p1', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p2 ', 'block_ram0p2', (' sectors',), None, 'kernel'),
        ('vibeOS: shell ready', 'shell_ready', (), None, 'user'),
    ],
    'gp_smp2': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: pmm: ', 'pmm_free_frames', (' free 4KiB frames',), None, 'kernel'),
        ('vibeOS: paging: cr3 ok', 'paging_cr3_ok', (), None, 'kernel'),
        ('vibeOS: paging: mmio uc', 'paging_mmio_uc', (), None, 'kernel'),
        ('vibeOS: heap ok', 'heap_ok', (), None, 'kernel'),
        ('vibeOS: kva: ready', 'kva_ready', (), None, 'kernel'),
        ('vibeOS: gdt ok', 'gdt_ok', (), None, 'kernel'),
        ('vibeOS: pic: remapped', 'pic_remapped', (), None, 'kernel'),
        ('vibeOS: idt ok', 'idt_ok', (), None, 'kernel'),
        ('vibeOS: per_cpu: bsp ready', 'per_cpu_bsp', (), None, 'kernel'),
        ('vibeOS: acpi: xsdt ', 'acpi_xsdt', (' tables',), None, 'kernel'),
        ('vibeOS: time: calibrated hpet ', 'time_calib_hpet', ('/ms',), None, 'kernel'),
        ('vibeOS: time: tsc ', 'time_tsc', ('/ms',), None, 'kernel'),
        ('vibeOS: time: lapic_timer ok (periodic)', 'lapic_timer_ok', (), None, 'kernel'),
        ('vibeOS: sched: cpu0 ready', 'sched_cpu0', (), None, 'kernel'),
        ('vibeOS: irq: enabled', 'irq_enabled', (), None, 'kernel'),
        ('vibeOS: sched: cpu1 ready', 'sched_cpu1', (), None, 'kernel'),
        ('vibeOS: smp: ap online', 'smp_ap_online_0', (), None, 'kernel'),
        ('vibeOS: smp: done', 'smp_done', (), ('vibeOS: smp: ap online', 1), 'kernel'),
        ('vibeOS: console ok', 'console_ok', (), None, 'kernel'),
        ('vibeOS: pci: ', 'pci_devices', (' devices',), None, 'kernel'),
        ('vibeOS: block: ram0 ', 'block_ramdisk', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p1 ', 'block_ram0p1', (' sectors',), None, 'kernel'),
        ('vibeOS: block: ram0p2 ', 'block_ram0p2', (' sectors',), None, 'kernel'),
        ('vibeOS: boot: gp-test armed', 'gp_test_armed', (), None, 'kernel'),
    ],
    'halt': [
        ('vibeOS: serial online', 'serial_online', (), None, 'kernel'),
        ('vibeOS: limine: rev 3 ok', 'limine_ok', (), None, 'kernel'),
        ('vibeOS: boot: panic-test armed', 'panic_test_armed', (), None, 'kernel'),
    ],
}
BRANCH_POINT_SIGNATURES: tuple[str, ...] = (
    "panicked at",
    "vibeOS: panic:",
    "#PF",
    "#GP",
    "#UD",
    "#DF",
    "double fault",
    "stack overflow",
    "vibeOS: vibefs: bad crash_plant",
)
BRANCH_POINT_USER_FAILURES: tuple[str, ...] = ('user: tests fail',)
BRANCH_POINT_LIMINE: tuple[str, ...] = ('PANIC(?:\\x1b\\[[0-9;]*m)*: ',)


def entry(m: Marker) -> Entry:
    return (
        m.substring,
        m.name,
        m.and_contains,
        m.exactly_before,
        m.source or frame.source_of(m.substring),
    )


def built(config: str) -> list[Entry]:
    with mock.patch.dict(os.environ, clear=True):
        if config == "halt":
            return [entry(m) for m in harness.halt_test_markers()]
        return [entry(m) for m in harness.boot_contract_markers(**CONFIGS[config])]


class TestContractLists(unittest.TestCase):
    """Each list the harness builds equals the branch point's."""

    def test_each_configuration(self) -> None:
        self.assertEqual(sorted(BRANCH_POINT), sorted([*CONFIGS, "halt"]))
        for config, want in BRANCH_POINT.items():
            with self.subTest(config=config):
                self.assertEqual(built(config), want)

    def test_panic_signatures(self) -> None:
        self.assertEqual(harness.PANIC_SIGNATURES, BRANCH_POINT_SIGNATURES)

    def test_user_and_limine_lists(self) -> None:
        self.assertEqual(frame.USER_FAILURES, BRANCH_POINT_USER_FAILURES)
        self.assertEqual(
            tuple(p.pattern for p in frame.LIMINE_SIGNATURES), BRANCH_POINT_LIMINE
        )

    def test_block_markers_equivalent(self) -> None:
        """The block markers' printed-order shape accepts and rejects the
        same lines as the branch point's `" <name> "` fragment did."""
        lines = [
            "vibeOS: block: ram0 256 sectors",
            "vibeOS: block: ram0p1 100 sectors",
            "vibeOS: block: ram0p2 156 sectors",
            "vibeOS: block: vda 2048 sectors",
            "vibeOS: block: vdap1 2000 sectors",
            "vibeOS: block: ram0",
            "ram0 256 sectors",
        ]
        for part, name in (
            ("ram0", "block_ramdisk"),
            ("ram0p1", "block_ram0p1"),
            ("ram0p2", "block_ram0p2"),
        ):
            old = Marker("vibeOS: block: ", name, and_contains=(f" {part} ", " sectors"))
            new = Marker(f"vibeOS: block: {part} ", name, and_contains=(" sectors",))
            for text in lines:
                with self.subTest(name=name, line=text):
                    raw = frame.FRAME + text
                    self.assertEqual(new.matches(raw), old.matches(raw))
            self.assertTrue(new.matches(frame.FRAME + f"vibeOS: block: {part} 9 sectors"))


if __name__ == "__main__":
    unittest.main()
