// @generated by scripts/gen_syscalls.py from crates/core/src/proc/syscalls.toml.
// Do not edit: change the table and run the script (ROADMAP §10.5).

//! x86_64 system call stubs (C-USERRT, C-SYSTABLE), generated from the
//! kernel's syscall table. Each takes its arguments in the C types of
//! Linux's prototype and returns `Ok` with the result or the `Errno`.
//! A stub is an `unsafe fn` when the kernel writes through one of its
//! pointers or the row says why.

use core::ffi::c_void;

/// The raw calls, for a call with no stub.
pub use super::{syscall0, syscall1, syscall2, syscall3, syscall4, syscall5, syscall6};
use crate::sys::{Errno, result};

/// The x86_64 numbers.
pub mod nr {
    /// `read`.
    pub const SYS_READ: usize = 0;
    /// `write`.
    pub const SYS_WRITE: usize = 1;
    /// `open`.
    pub const SYS_OPEN: usize = 2;
    /// `close`.
    pub const SYS_CLOSE: usize = 3;
    /// `lseek`.
    pub const SYS_LSEEK: usize = 8;
    /// `mmap`.
    pub const SYS_MMAP: usize = 9;
    /// `munmap`.
    pub const SYS_MUNMAP: usize = 11;
    /// `brk`.
    pub const SYS_BRK: usize = 12;
    /// `sched_yield`.
    pub const SYS_SCHED_YIELD: usize = 24;
    /// `dup`.
    pub const SYS_DUP: usize = 32;
    /// `dup2`.
    pub const SYS_DUP2: usize = 33;
    /// `getpid`.
    pub const SYS_GETPID: usize = 39;
    /// `fork`.
    pub const SYS_FORK: usize = 57;
    /// `execve`.
    pub const SYS_EXECVE: usize = 59;
    /// `exit`.
    pub const SYS_EXIT: usize = 60;
    /// `wait4`.
    pub const SYS_WAIT4: usize = 61;
    /// `kill`.
    pub const SYS_KILL: usize = 62;
    /// `fcntl`.
    pub const SYS_FCNTL: usize = 72;
    /// `getppid`.
    pub const SYS_GETPPID: usize = 110;
    /// `psinfo`.
    pub const SYS_PSINFO: usize = 500;
}

/// One system call.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Sys {
    /// `read`.
    Read,
    /// `write`.
    Write,
    /// `open`.
    Open,
    /// `close`.
    Close,
    /// `lseek`.
    Lseek,
    /// `mmap`.
    Mmap,
    /// `munmap`.
    Munmap,
    /// `brk`.
    Brk,
    /// `sched_yield`.
    SchedYield,
    /// `dup`.
    Dup,
    /// `dup2`.
    Dup2,
    /// `getpid`.
    Getpid,
    /// `fork`.
    Fork,
    /// `execve`.
    Execve,
    /// `exit`.
    Exit,
    /// `wait4`.
    Wait4,
    /// `kill`.
    Kill,
    /// `fcntl`.
    Fcntl,
    /// `getppid`.
    Getppid,
    /// `psinfo`.
    Psinfo,
}

impl Sys {
    /// Every call, in table order.
    pub const ALL: [Sys; 20] = [
        Sys::Read,
        Sys::Write,
        Sys::Open,
        Sys::Close,
        Sys::Lseek,
        Sys::Mmap,
        Sys::Munmap,
        Sys::Brk,
        Sys::SchedYield,
        Sys::Dup,
        Sys::Dup2,
        Sys::Getpid,
        Sys::Fork,
        Sys::Execve,
        Sys::Exit,
        Sys::Wait4,
        Sys::Kill,
        Sys::Fcntl,
        Sys::Getppid,
        Sys::Psinfo,
    ];

    /// The call named `name`.
    pub fn from_name(name: &[u8]) -> Option<Sys> {
        match name {
            b"read" => Some(Sys::Read),
            b"write" => Some(Sys::Write),
            b"open" => Some(Sys::Open),
            b"close" => Some(Sys::Close),
            b"lseek" => Some(Sys::Lseek),
            b"mmap" => Some(Sys::Mmap),
            b"munmap" => Some(Sys::Munmap),
            b"brk" => Some(Sys::Brk),
            b"sched_yield" => Some(Sys::SchedYield),
            b"dup" => Some(Sys::Dup),
            b"dup2" => Some(Sys::Dup2),
            b"getpid" => Some(Sys::Getpid),
            b"fork" => Some(Sys::Fork),
            b"execve" => Some(Sys::Execve),
            b"exit" => Some(Sys::Exit),
            b"wait4" => Some(Sys::Wait4),
            b"kill" => Some(Sys::Kill),
            b"fcntl" => Some(Sys::Fcntl),
            b"getppid" => Some(Sys::Getppid),
            b"psinfo" => Some(Sys::Psinfo),
            _ => None,
        }
    }

    /// The call's name.
    pub const fn name(self) -> &'static str {
        match self {
            Sys::Read => "read",
            Sys::Write => "write",
            Sys::Open => "open",
            Sys::Close => "close",
            Sys::Lseek => "lseek",
            Sys::Mmap => "mmap",
            Sys::Munmap => "munmap",
            Sys::Brk => "brk",
            Sys::SchedYield => "sched_yield",
            Sys::Dup => "dup",
            Sys::Dup2 => "dup2",
            Sys::Getpid => "getpid",
            Sys::Fork => "fork",
            Sys::Execve => "execve",
            Sys::Exit => "exit",
            Sys::Wait4 => "wait4",
            Sys::Kill => "kill",
            Sys::Fcntl => "fcntl",
            Sys::Getppid => "getppid",
            Sys::Psinfo => "psinfo",
        }
    }

    /// The call's number.
    pub const fn nr(self) -> usize {
        match self {
            Sys::Read => nr::SYS_READ,
            Sys::Write => nr::SYS_WRITE,
            Sys::Open => nr::SYS_OPEN,
            Sys::Close => nr::SYS_CLOSE,
            Sys::Lseek => nr::SYS_LSEEK,
            Sys::Mmap => nr::SYS_MMAP,
            Sys::Munmap => nr::SYS_MUNMAP,
            Sys::Brk => nr::SYS_BRK,
            Sys::SchedYield => nr::SYS_SCHED_YIELD,
            Sys::Dup => nr::SYS_DUP,
            Sys::Dup2 => nr::SYS_DUP2,
            Sys::Getpid => nr::SYS_GETPID,
            Sys::Fork => nr::SYS_FORK,
            Sys::Execve => nr::SYS_EXECVE,
            Sys::Exit => nr::SYS_EXIT,
            Sys::Wait4 => nr::SYS_WAIT4,
            Sys::Kill => nr::SYS_KILL,
            Sys::Fcntl => nr::SYS_FCNTL,
            Sys::Getppid => nr::SYS_GETPPID,
            Sys::Psinfo => nr::SYS_PSINFO,
        }
    }

    /// The call's argument names, in register order.
    pub const fn args(self) -> &'static [&'static str] {
        match self {
            Sys::Read => &["fd", "buf", "count"],
            Sys::Write => &["fd", "buf", "count"],
            Sys::Open => &["pathname", "flags", "mode"],
            Sys::Close => &["fd"],
            Sys::Lseek => &["fd", "offset", "whence"],
            Sys::Mmap => &["addr", "length", "prot", "flags", "fd", "offset"],
            Sys::Munmap => &["addr", "length"],
            Sys::Brk => &["addr"],
            Sys::SchedYield => &[],
            Sys::Dup => &["oldfd"],
            Sys::Dup2 => &["oldfd", "newfd"],
            Sys::Getpid => &[],
            Sys::Fork => &[],
            Sys::Execve => &["pathname", "argv", "envp"],
            Sys::Exit => &["status"],
            Sys::Wait4 => &["pid", "wstatus", "options", "rusage"],
            Sys::Kill => &["pid", "sig"],
            Sys::Fcntl => &["fd", "cmd", "arg"],
            Sys::Getppid => &[],
            Sys::Psinfo => &["buf", "len"],
        }
    }
}

/// `read(unsigned int fd, char *buf, size_t count)`.
///
/// # Safety
///
/// The kernel writes up to `count` bytes through `buf`: no live Rust reference may cover them.
pub unsafe fn read(fd: u32, buf: *mut u8, count: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall3(nr::SYS_READ, fd as usize, buf as usize, count) })
}

/// `write(unsigned int fd, const char *buf, size_t count)`.
pub fn write(fd: u32, buf: *const u8, count: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall3(nr::SYS_WRITE, fd as usize, buf as usize, count) })
}

/// `open(const char *pathname, int flags, umode_t mode)`: `pathname` at most 255 bytes.
pub fn open(pathname: *const u8, flags: i32, mode: u16) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall3(
            nr::SYS_OPEN,
            pathname as usize,
            flags as isize as usize,
            mode as usize,
        )
    })
}

/// `close(unsigned int fd)`.
pub fn close(fd: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall1(nr::SYS_CLOSE, fd as usize) })
}

/// `lseek(unsigned int fd, off_t offset, unsigned int whence)`.
pub fn lseek(fd: u32, offset: i64, whence: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall3(
            nr::SYS_LSEEK,
            fd as usize,
            offset as isize as usize,
            whence as usize,
        )
    })
}

/// `mmap(unsigned long addr, unsigned long length, unsigned long prot, unsigned long flags,
/// unsigned long fd, unsigned long offset)`: anonymous and private only; returns the address.
///
/// # Safety
///
/// A mapping can replace memory the program uses.
pub unsafe fn mmap(
    addr: u64,
    length: u64,
    prot: u64,
    flags: u64,
    fd: u64,
    offset: u64,
) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe {
        syscall6(
            nr::SYS_MMAP,
            addr as usize,
            length as usize,
            prot as usize,
            flags as usize,
            fd as usize,
            offset as usize,
        )
    })
}

/// `munmap(unsigned long addr, size_t length)`.
///
/// # Safety
///
/// The range can hold memory the program still uses.
pub unsafe fn munmap(addr: u64, length: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall2(nr::SYS_MUNMAP, addr as usize, length) })
}

/// `brk(unsigned long addr)`: returns the break; `0` if the caller is not a process.
///
/// # Safety
///
/// Shrinking the break unmaps memory the program may still use.
pub unsafe fn brk(addr: u64) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall1(nr::SYS_BRK, addr as usize) })
}

/// `sched_yield()`.
pub fn sched_yield() -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall0(nr::SYS_SCHED_YIELD) })
}

/// `dup(unsigned int oldfd)`: CLOEXEC cleared on the new fd.
pub fn dup(oldfd: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall1(nr::SYS_DUP, oldfd as usize) })
}

/// `dup2(unsigned int oldfd, unsigned int newfd)`.
pub fn dup2(oldfd: u32, newfd: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall2(nr::SYS_DUP2, oldfd as usize, newfd as usize) })
}

/// `getpid()`: `0` if the caller is not a process.
pub fn getpid() -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall0(nr::SYS_GETPID) })
}

/// `fork()`: full address-space copy; the child returns 0.
pub fn fork() -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall0(nr::SYS_FORK) })
}

/// `execve(const char *pathname, const char *const *argv, const char *const *envp)`: `argv` at most
/// 15 strings of at most 255 bytes each; `envp` not read.
pub fn execve(
    pathname: *const u8,
    argv: *const *const u8,
    envp: *const *const u8,
) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall3(
            nr::SYS_EXECVE,
            pathname as usize,
            argv as usize,
            envp as usize,
        )
    })
}

/// `exit(int status)`: the low 8 bits of `status`.
pub fn exit(status: i32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall1(nr::SYS_EXIT, status as isize as usize) })
}

/// `wait4(pid_t pid, int *wstatus, int options, struct rusage *rusage)`.
///
/// # Safety
///
/// The kernel writes 4 bytes through `wstatus`, unless it is null: no live Rust reference may cover
/// them.
pub unsafe fn wait4(
    pid: i32,
    wstatus: *mut i32,
    options: i32,
    rusage: *mut c_void,
) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe {
        syscall4(
            nr::SYS_WAIT4,
            pid as isize as usize,
            wstatus as usize,
            options as isize as usize,
            rusage as usize,
        )
    })
}

/// `kill(pid_t pid, int sig)`: default actions only.
pub fn kill(pid: i32, sig: i32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall2(nr::SYS_KILL, pid as isize as usize, sig as isize as usize) })
}

/// `fcntl(unsigned int fd, unsigned int cmd, unsigned long arg)`: `F_GETFD` and `F_SETFD`
/// (`FD_CLOEXEC`) only.
pub fn fcntl(fd: u32, cmd: u32, arg: u64) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall3(nr::SYS_FCNTL, fd as usize, cmd as usize, arg as usize) })
}

/// `getppid()`.
pub fn getppid() -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall0(nr::SYS_GETPPID) })
}

/// `psinfo(char *buf, size_t len)`: vibeOS-specific (SYSCALL.md §8; LINUX.md `psinfo`).
///
/// # Safety
///
/// The kernel writes up to `len` bytes through `buf`: no live Rust reference may cover them.
pub unsafe fn psinfo(buf: *mut u8, len: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall2(nr::SYS_PSINFO, buf as usize, len) })
}
