// @generated by scripts/gen_syscalls.py from crates/core/src/proc/syscalls.toml.
// Do not edit: change the table and run the script (ROADMAP §10.5).

//! aarch64 system call stubs (C-USERRT, C-SYSTABLE), generated from the
//! kernel's syscall table. Each takes its arguments in the C types of
//! Linux's prototype and returns `Ok` with the result or the `Errno`.
//! A stub is an `unsafe fn` when the kernel writes through one of its
//! pointers or the row says why. `open`, `dup2`, and `fork` are
//! wrappers onto `openat`/`dup3`/`clone` (ROADMAP §11.6).

use core::ffi::c_void;

/// The raw calls, for a call with no stub.
pub use super::{syscall0, syscall1, syscall2, syscall3, syscall4, syscall5, syscall6};
use crate::sys::{Errno, result};

/// The aarch64 numbers.
pub mod nr {
    /// `read`.
    pub const SYS_READ: usize = 63;
    /// `write`.
    pub const SYS_WRITE: usize = 64;
    /// `close`.
    pub const SYS_CLOSE: usize = 57;
    /// `fstat`.
    pub const SYS_FSTAT: usize = 80;
    /// `lseek`.
    pub const SYS_LSEEK: usize = 62;
    /// `mmap`.
    pub const SYS_MMAP: usize = 222;
    /// `munmap`.
    pub const SYS_MUNMAP: usize = 215;
    /// `brk`.
    pub const SYS_BRK: usize = 214;
    /// `sched_yield`.
    pub const SYS_SCHED_YIELD: usize = 124;
    /// `dup`.
    pub const SYS_DUP: usize = 23;
    /// `nanosleep`.
    pub const SYS_NANOSLEEP: usize = 101;
    /// `getpid`.
    pub const SYS_GETPID: usize = 172;
    /// `execve`.
    pub const SYS_EXECVE: usize = 221;
    /// `exit`.
    pub const SYS_EXIT: usize = 93;
    /// `wait4`.
    pub const SYS_WAIT4: usize = 260;
    /// `kill`.
    pub const SYS_KILL: usize = 129;
    /// `fcntl`.
    pub const SYS_FCNTL: usize = 25;
    /// `getppid`.
    pub const SYS_GETPPID: usize = 173;
    /// `reboot`.
    pub const SYS_REBOOT: usize = 142;
    /// `getdents64`.
    pub const SYS_GETDENTS64: usize = 61;
    /// `psinfo`.
    pub const SYS_PSINFO: usize = 500;
    /// `openat`.
    pub const SYS_OPENAT: usize = 56;
    /// `dup3`.
    pub const SYS_DUP3: usize = 24;
    /// `clone`.
    pub const SYS_CLONE: usize = 220;
    /// `open` as `openat(AT_FDCWD, …)`.
    pub const SYS_OPEN: usize = SYS_OPENAT;
    /// `dup2` as `dup3(…, 0)` except `oldfd == newfd`.
    pub const SYS_DUP2: usize = SYS_DUP3;
    /// `fork` as `clone(SIGCHLD, 0, …)`.
    pub const SYS_FORK: usize = SYS_CLONE;
}

/// One system call.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Sys {
    /// `read`.
    Read,
    /// `write`.
    Write,
    /// `open`.
    Open,
    /// `close`.
    Close,
    /// `fstat`.
    Fstat,
    /// `lseek`.
    Lseek,
    /// `mmap`.
    Mmap,
    /// `munmap`.
    Munmap,
    /// `brk`.
    Brk,
    /// `sched_yield`.
    SchedYield,
    /// `dup`.
    Dup,
    /// `dup2`.
    Dup2,
    /// `nanosleep`.
    Nanosleep,
    /// `getpid`.
    Getpid,
    /// `fork`.
    Fork,
    /// `execve`.
    Execve,
    /// `exit`.
    Exit,
    /// `wait4`.
    Wait4,
    /// `kill`.
    Kill,
    /// `fcntl`.
    Fcntl,
    /// `getppid`.
    Getppid,
    /// `reboot`.
    Reboot,
    /// `getdents64`.
    Getdents64,
    /// `psinfo`.
    Psinfo,
    /// `openat`.
    Openat,
    /// `dup3`.
    Dup3,
    /// `clone`.
    Clone,
}

impl Sys {
    /// Every call, in table order.
    pub const ALL: [Sys; 27] = [
        Sys::Read,
        Sys::Write,
        Sys::Open,
        Sys::Close,
        Sys::Fstat,
        Sys::Lseek,
        Sys::Mmap,
        Sys::Munmap,
        Sys::Brk,
        Sys::SchedYield,
        Sys::Dup,
        Sys::Dup2,
        Sys::Nanosleep,
        Sys::Getpid,
        Sys::Fork,
        Sys::Execve,
        Sys::Exit,
        Sys::Wait4,
        Sys::Kill,
        Sys::Fcntl,
        Sys::Getppid,
        Sys::Reboot,
        Sys::Getdents64,
        Sys::Psinfo,
        Sys::Openat,
        Sys::Dup3,
        Sys::Clone,
    ];

    /// The call named `name`.
    pub fn from_name(name: &[u8]) -> Option<Sys> {
        match name {
            b"read" => Some(Sys::Read),
            b"write" => Some(Sys::Write),
            b"open" => Some(Sys::Open),
            b"close" => Some(Sys::Close),
            b"fstat" => Some(Sys::Fstat),
            b"lseek" => Some(Sys::Lseek),
            b"mmap" => Some(Sys::Mmap),
            b"munmap" => Some(Sys::Munmap),
            b"brk" => Some(Sys::Brk),
            b"sched_yield" => Some(Sys::SchedYield),
            b"dup" => Some(Sys::Dup),
            b"dup2" => Some(Sys::Dup2),
            b"nanosleep" => Some(Sys::Nanosleep),
            b"getpid" => Some(Sys::Getpid),
            b"fork" => Some(Sys::Fork),
            b"execve" => Some(Sys::Execve),
            b"exit" => Some(Sys::Exit),
            b"wait4" => Some(Sys::Wait4),
            b"kill" => Some(Sys::Kill),
            b"fcntl" => Some(Sys::Fcntl),
            b"getppid" => Some(Sys::Getppid),
            b"reboot" => Some(Sys::Reboot),
            b"getdents64" => Some(Sys::Getdents64),
            b"psinfo" => Some(Sys::Psinfo),
            b"openat" => Some(Sys::Openat),
            b"dup3" => Some(Sys::Dup3),
            b"clone" => Some(Sys::Clone),
            _ => None,
        }
    }

    /// The call's name.
    pub const fn name(self) -> &'static str {
        match self {
            Sys::Read => "read",
            Sys::Write => "write",
            Sys::Open => "open",
            Sys::Close => "close",
            Sys::Fstat => "fstat",
            Sys::Lseek => "lseek",
            Sys::Mmap => "mmap",
            Sys::Munmap => "munmap",
            Sys::Brk => "brk",
            Sys::SchedYield => "sched_yield",
            Sys::Dup => "dup",
            Sys::Dup2 => "dup2",
            Sys::Nanosleep => "nanosleep",
            Sys::Getpid => "getpid",
            Sys::Fork => "fork",
            Sys::Execve => "execve",
            Sys::Exit => "exit",
            Sys::Wait4 => "wait4",
            Sys::Kill => "kill",
            Sys::Fcntl => "fcntl",
            Sys::Getppid => "getppid",
            Sys::Reboot => "reboot",
            Sys::Getdents64 => "getdents64",
            Sys::Psinfo => "psinfo",
            Sys::Openat => "openat",
            Sys::Dup3 => "dup3",
            Sys::Clone => "clone",
        }
    }

    /// The call's number.
    pub const fn nr(self) -> usize {
        match self {
            Sys::Read => nr::SYS_READ,
            Sys::Write => nr::SYS_WRITE,
            Sys::Open => nr::SYS_OPEN,
            Sys::Close => nr::SYS_CLOSE,
            Sys::Fstat => nr::SYS_FSTAT,
            Sys::Lseek => nr::SYS_LSEEK,
            Sys::Mmap => nr::SYS_MMAP,
            Sys::Munmap => nr::SYS_MUNMAP,
            Sys::Brk => nr::SYS_BRK,
            Sys::SchedYield => nr::SYS_SCHED_YIELD,
            Sys::Dup => nr::SYS_DUP,
            Sys::Dup2 => nr::SYS_DUP2,
            Sys::Nanosleep => nr::SYS_NANOSLEEP,
            Sys::Getpid => nr::SYS_GETPID,
            Sys::Fork => nr::SYS_FORK,
            Sys::Execve => nr::SYS_EXECVE,
            Sys::Exit => nr::SYS_EXIT,
            Sys::Wait4 => nr::SYS_WAIT4,
            Sys::Kill => nr::SYS_KILL,
            Sys::Fcntl => nr::SYS_FCNTL,
            Sys::Getppid => nr::SYS_GETPPID,
            Sys::Reboot => nr::SYS_REBOOT,
            Sys::Getdents64 => nr::SYS_GETDENTS64,
            Sys::Psinfo => nr::SYS_PSINFO,
            Sys::Openat => nr::SYS_OPENAT,
            Sys::Dup3 => nr::SYS_DUP3,
            Sys::Clone => nr::SYS_CLONE,
        }
    }

    /// The call's argument names, in register order.
    pub const fn args(self) -> &'static [&'static str] {
        match self {
            Sys::Read => &["fd", "buf", "count"],
            Sys::Write => &["fd", "buf", "count"],
            Sys::Open => &["pathname", "flags", "mode"],
            Sys::Close => &["fd"],
            Sys::Fstat => &["fd", "statbuf"],
            Sys::Lseek => &["fd", "offset", "whence"],
            Sys::Mmap => &["addr", "length", "prot", "flags", "fd", "offset"],
            Sys::Munmap => &["addr", "length"],
            Sys::Brk => &["addr"],
            Sys::SchedYield => &[],
            Sys::Dup => &["oldfd"],
            Sys::Dup2 => &["oldfd", "newfd"],
            Sys::Nanosleep => &["rqtp", "rmtp"],
            Sys::Getpid => &[],
            Sys::Fork => &[],
            Sys::Execve => &["pathname", "argv", "envp"],
            Sys::Exit => &["status"],
            Sys::Wait4 => &["pid", "wstatus", "options", "rusage"],
            Sys::Kill => &["pid", "sig"],
            Sys::Fcntl => &["fd", "cmd", "arg"],
            Sys::Getppid => &[],
            Sys::Reboot => &["magic1", "magic2", "cmd", "arg"],
            Sys::Getdents64 => &["fd", "dirent", "count"],
            Sys::Psinfo => &["buf", "len"],
            Sys::Openat => &["dfd", "filename", "flags", "mode"],
            Sys::Dup3 => &["oldfd", "newfd", "flags"],
            Sys::Clone => &["flags", "newsp", "parent_tid", "tls", "child_tid"],
        }
    }
}

/// `read(unsigned int fd, char *buf, size_t count)`.
///
/// # Safety
///
/// The kernel writes up to `count` bytes through `buf`: no live Rust reference may cover them.
pub unsafe fn read(fd: u32, buf: *mut u8, count: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall3(nr::SYS_READ, fd as usize, buf as usize, count) })
}

/// `write(unsigned int fd, const char *buf, size_t count)`.
pub fn write(fd: u32, buf: *const u8, count: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall3(nr::SYS_WRITE, fd as usize, buf as usize, count) })
}

/// `close(unsigned int fd)`.
pub fn close(fd: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall1(nr::SYS_CLOSE, fd as usize) })
}

/// `fstat(unsigned int fd, struct stat *statbuf)`: x86_64 144-byte `struct stat`; aarch64 128-byte
/// asm-generic; see SYSCALL.md §3.1.
///
/// # Safety
///
/// The kernel writes 128 bytes through `statbuf`: no live Rust reference may cover them.
pub unsafe fn fstat(fd: u32, statbuf: *mut c_void) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall2(nr::SYS_FSTAT, fd as usize, statbuf as usize) })
}

/// `lseek(unsigned int fd, off_t offset, unsigned int whence)`.
pub fn lseek(fd: u32, offset: i64, whence: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall3(
            nr::SYS_LSEEK,
            fd as usize,
            offset as isize as usize,
            whence as usize,
        )
    })
}

/// `mmap(unsigned long addr, unsigned long length, unsigned long prot, unsigned long flags,
/// unsigned long fd, unsigned long offset)`: anonymous and private only; returns the address.
///
/// # Safety
///
/// A mapping can replace memory the program uses.
pub unsafe fn mmap(
    addr: u64,
    length: u64,
    prot: u64,
    flags: u64,
    fd: u64,
    offset: u64,
) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe {
        syscall6(
            nr::SYS_MMAP,
            addr as usize,
            length as usize,
            prot as usize,
            flags as usize,
            fd as usize,
            offset as usize,
        )
    })
}

/// `munmap(unsigned long addr, size_t length)`.
///
/// # Safety
///
/// The range can hold memory the program still uses.
pub unsafe fn munmap(addr: u64, length: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall2(nr::SYS_MUNMAP, addr as usize, length) })
}

/// `brk(unsigned long addr)`: returns the break; `0` if the caller is not a process.
///
/// # Safety
///
/// Shrinking the break unmaps memory the program may still use.
pub unsafe fn brk(addr: u64) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall1(nr::SYS_BRK, addr as usize) })
}

/// `sched_yield()`.
pub fn sched_yield() -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall0(nr::SYS_SCHED_YIELD) })
}

/// `dup(unsigned int oldfd)`: CLOEXEC cleared on the new fd.
pub fn dup(oldfd: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall1(nr::SYS_DUP, oldfd as usize) })
}

/// `nanosleep(const struct __kernel_timespec *rqtp, struct __kernel_timespec *rmtp)`:
/// `CLOCK_MONOTONIC`, rounded up to the tick; see SYSCALL.md §3.1.
pub fn nanosleep(rqtp: *const c_void, rmtp: *mut c_void) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall2(nr::SYS_NANOSLEEP, rqtp as usize, rmtp as usize) })
}

/// `getpid()`: `0` if the caller is not a process.
pub fn getpid() -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall0(nr::SYS_GETPID) })
}

/// `execve(const char *pathname, const char *const *argv, const char *const *envp)`: `argv` and
/// `envp`: NULL-terminated vectors of C strings, copied to the new stack under Linux's limits
/// (§3.1).
pub fn execve(
    pathname: *const u8,
    argv: *const *const u8,
    envp: *const *const u8,
) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall3(
            nr::SYS_EXECVE,
            pathname as usize,
            argv as usize,
            envp as usize,
        )
    })
}

/// `exit(int status)`: the low 8 bits of `status`.
pub fn exit(status: i32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall1(nr::SYS_EXIT, status as isize as usize) })
}

/// `wait4(pid_t pid, int *wstatus, int options, struct rusage *rusage)`.
///
/// # Safety
///
/// The kernel writes 4 bytes through `wstatus`, unless it is null: no live Rust reference may cover
/// them.
pub unsafe fn wait4(
    pid: i32,
    wstatus: *mut i32,
    options: i32,
    rusage: *mut c_void,
) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe {
        syscall4(
            nr::SYS_WAIT4,
            pid as isize as usize,
            wstatus as usize,
            options as isize as usize,
            rusage as usize,
        )
    })
}

/// `kill(pid_t pid, int sig)`: default actions only.
pub fn kill(pid: i32, sig: i32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall2(nr::SYS_KILL, pid as isize as usize, sig as isize as usize) })
}

/// `fcntl(unsigned int fd, unsigned int cmd, unsigned long arg)`: `F_GETFD` and `F_SETFD`
/// (`FD_CLOEXEC`) only.
pub fn fcntl(fd: u32, cmd: u32, arg: u64) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall3(nr::SYS_FCNTL, fd as usize, cmd as usize, arg as usize) })
}

/// `getppid()`.
pub fn getppid() -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe { syscall0(nr::SYS_GETPPID) })
}

/// `reboot(int magic1, int magic2, unsigned int cmd, void *arg)`: power off and restart; see
/// SYSCALL.md §3.1.
pub fn reboot(magic1: i32, magic2: i32, cmd: u32, arg: *mut c_void) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall4(
            nr::SYS_REBOOT,
            magic1 as isize as usize,
            magic2 as isize as usize,
            cmd as usize,
            arg as usize,
        )
    })
}

/// `getdents64(unsigned int fd, struct linux_dirent64 *dirent, unsigned int count)`: at most 512
/// bytes a call; see SYSCALL.md §3.1.
///
/// # Safety
///
/// The kernel writes up to `count` bytes through `dirent`: no live Rust reference may cover them.
pub unsafe fn getdents64(fd: u32, dirent: *mut c_void, count: u32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe {
        syscall3(
            nr::SYS_GETDENTS64,
            fd as usize,
            dirent as usize,
            count as usize,
        )
    })
}

/// `psinfo(char *buf, size_t len)`: vibeOS-specific (SYSCALL.md §8; LINUX.md `psinfo`).
///
/// # Safety
///
/// The kernel writes up to `len` bytes through `buf`: no live Rust reference may cover them.
pub unsafe fn psinfo(buf: *mut u8, len: usize) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention, and this fn's `# Safety`
    // contract for what the call writes, established here by its caller.
    result(unsafe { syscall2(nr::SYS_PSINFO, buf as usize, len) })
}

/// `openat(int dfd, const char *filename, int flags, umode_t mode)`: `AT_FDCWD` is -100; `filename`
/// at most 255 bytes.
pub fn openat(dfd: i32, filename: *const u8, flags: i32, mode: u16) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall4(
            nr::SYS_OPENAT,
            dfd as isize as usize,
            filename as usize,
            flags as isize as usize,
            mode as usize,
        )
    })
}

/// `dup3(unsigned int oldfd, unsigned int newfd, int flags)`: `flags` is 0 or `O_CLOEXEC`; `oldfd
/// == newfd` is `EINVAL`.
pub fn dup3(oldfd: u32, newfd: u32, flags: i32) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall3(
            nr::SYS_DUP3,
            oldfd as usize,
            newfd as usize,
            flags as isize as usize,
        )
    })
}

/// `clone(unsigned long flags, unsigned long newsp, int *parent_tid, int *child_tid, unsigned long
/// tls)`: fork semantics only: `flags` must be `SIGCHLD` and `newsp` 0; arm64 swaps `tls` and
/// `child_tid`.
pub fn clone(
    flags: u64,
    newsp: u64,
    parent_tid: *mut i32,
    child_tid: *mut i32,
    tls: u64,
) -> Result<usize, Errno> {
    // SAFETY: the kernel's `syscall` convention; the kernel writes through
    // none of its pointers, established here by the table row.
    result(unsafe {
        syscall5(
            nr::SYS_CLONE,
            flags as usize,
            newsp as usize,
            parent_tid as usize,
            tls as usize,
            child_tid as usize,
        )
    })
}

/// `open` as `openat(AT_FDCWD, pathname, flags, mode)`.
pub fn open(pathname: *const u8, flags: i32, mode: u16) -> Result<usize, Errno> {
    openat(-100, pathname, flags, mode)
}

/// `dup2`: `dup3(oldfd, newfd, 0)`, or `fcntl(F_GETFD)` when equal.
pub fn dup2(oldfd: u32, newfd: u32) -> Result<usize, Errno> {
    if oldfd == newfd {
        fcntl(oldfd, 1, 0).map(|_| oldfd as usize)
    } else {
        dup3(oldfd, newfd, 0)
    }
}

/// `fork` as `clone(SIGCHLD, 0, …)`.
pub fn fork() -> Result<usize, Errno> {
    clone(17, 0, core::ptr::null_mut(), core::ptr::null_mut(), 0)
}

/// `limits::MAX_PROCS`: the process table's slots, zombies included.
pub const MAX_PROCS: usize = 256;
/// The user canonical half's exclusive end (DESIGN §4.1).
pub const USER_END: u64 = 0x0000_8000_0000_0000;
/// The exclusive end of what a user mapping may cover (C-USERMAPEND).
pub const USER_MAP_END: u64 = 0x0000_7FFF_FFFF_F000;

/// How the kernel copies through a pointer argument (SYSCALL.md §3).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PtrKind {
    /// A buffer whose length another argument holds.
    Buf,
    /// A fixed number of bytes.
    Fixed,
    /// A NUL-terminated string the kernel reads.
    Cstr,
    /// A NULL-terminated array of C strings the kernel reads.
    Strvec,
}

/// One declared pointer argument.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Ptr {
    /// Its register index.
    pub arg: usize,
    /// Its name.
    pub name: &'static str,
    /// How the kernel copies through it.
    pub kind: PtrKind,
    /// Whether the kernel writes through it (`dir = "out"`).
    pub out: bool,
    /// Whether NULL is valid and copies nothing.
    pub nullable: bool,
    /// The register index of a `Buf`'s length.
    pub len_from: Option<usize>,
    /// A `Fixed` pointer's size in bytes.
    pub size: usize,
}

/// One call's row: its errors and its declared pointers.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Call {
    /// The call.
    pub sys: Sys,
    /// Every errno its handler returns (SYSCALL.md §3).
    pub errors: &'static [Errno],
    /// The errnos only a kernel fault produces, each with the in-guest
    /// test that provokes it.
    pub ktest: &'static [(Errno, &'static str)],
    /// Its pointer arguments, but those the kernel does not read yet.
    pub ptrs: &'static [Ptr],
}

/// Every row with a aarch64 number, in table order.
#[rustfmt::skip]
pub const CALLS: &[Call] = &[
    Call {
        sys: Sys::Read,
        errors: &[Errno::EBADF, Errno::EFAULT, Errno::EISDIR, Errno::EAGAIN, Errno::EIO],
        ktest: &[(Errno::EAGAIN, "dev_random_eagain"), (Errno::EIO, "fat_bad_sector_eio")],
        ptrs: &[
            Ptr { arg: 1, name: "buf", kind: PtrKind::Buf, out: true, nullable: false, len_from: Some(2), size: 0 },
        ],
    },
    Call {
        sys: Sys::Write,
        errors: &[Errno::EBADF, Errno::EFAULT, Errno::EINVAL, Errno::EFBIG, Errno::ENOSPC, Errno::EIO],
        ktest: &[(Errno::EIO, "fat_bad_sector_eio")],
        ptrs: &[
            Ptr { arg: 1, name: "buf", kind: PtrKind::Buf, out: false, nullable: false, len_from: Some(2), size: 0 },
        ],
    },
    Call {
        sys: Sys::Open,
        errors: &[Errno::EFAULT, Errno::ENAMETOOLONG, Errno::EINVAL, Errno::ENOENT, Errno::ENOTDIR, Errno::EISDIR, Errno::EEXIST, Errno::EACCES, Errno::ELOOP, Errno::EMFILE, Errno::ENFILE, Errno::ENOSPC, Errno::ENOMEM, Errno::EIO],
        ktest: &[(Errno::EIO, "fat_bad_sector_eio"), (Errno::ENOMEM, "kalloc_nomem")],
        ptrs: &[
            Ptr { arg: 0, name: "pathname", kind: PtrKind::Cstr, out: false, nullable: false, len_from: None, size: 0 },
        ],
    },
    Call {
        sys: Sys::Close,
        errors: &[Errno::EBADF],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Fstat,
        errors: &[Errno::EBADF, Errno::EFAULT],
        ktest: &[],
        ptrs: &[
            Ptr { arg: 1, name: "statbuf", kind: PtrKind::Fixed, out: true, nullable: false, len_from: None, size: 128 },
        ],
    },
    Call {
        sys: Sys::Lseek,
        errors: &[Errno::EBADF, Errno::ESPIPE, Errno::EINVAL, Errno::ENXIO],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Mmap,
        errors: &[Errno::EINVAL, Errno::EBADF, Errno::ENODEV, Errno::ENOMEM, Errno::EPERM, Errno::EEXIST],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Munmap,
        errors: &[Errno::EINVAL, Errno::ENOMEM],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Brk,
        errors: &[],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::SchedYield,
        errors: &[],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Dup,
        errors: &[Errno::EBADF, Errno::EMFILE],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Dup2,
        errors: &[Errno::EBADF],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Nanosleep,
        errors: &[Errno::EFAULT, Errno::EINVAL],
        ktest: &[],
        ptrs: &[
            Ptr { arg: 0, name: "rqtp", kind: PtrKind::Fixed, out: false, nullable: false, len_from: None, size: 16 },
        ],
    },
    Call {
        sys: Sys::Getpid,
        errors: &[],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Fork,
        errors: &[Errno::EAGAIN, Errno::ENOMEM],
        ktest: &[(Errno::ENOMEM, "fork_oom")],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Execve,
        errors: &[Errno::EFAULT, Errno::ENAMETOOLONG, Errno::ENOENT, Errno::ENOTDIR, Errno::EACCES, Errno::ELOOP, Errno::ENFILE, Errno::E2BIG, Errno::ENOEXEC, Errno::ENOMEM, Errno::EIO],
        ktest: &[(Errno::EIO, "fat_bad_sector_eio")],
        ptrs: &[
            Ptr { arg: 0, name: "pathname", kind: PtrKind::Cstr, out: false, nullable: false, len_from: None, size: 0 },
            Ptr { arg: 1, name: "argv", kind: PtrKind::Strvec, out: false, nullable: true, len_from: None, size: 0 },
            Ptr { arg: 2, name: "envp", kind: PtrKind::Strvec, out: false, nullable: true, len_from: None, size: 0 },
        ],
    },
    Call {
        sys: Sys::Exit,
        errors: &[],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Wait4,
        errors: &[Errno::ECHILD, Errno::EFAULT],
        ktest: &[],
        ptrs: &[
            Ptr { arg: 1, name: "wstatus", kind: PtrKind::Fixed, out: true, nullable: true, len_from: None, size: 4 },
        ],
    },
    Call {
        sys: Sys::Kill,
        errors: &[Errno::EINVAL, Errno::ESRCH],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Fcntl,
        errors: &[Errno::EBADF, Errno::EINVAL],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Getppid,
        errors: &[],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Reboot,
        errors: &[Errno::EINVAL, Errno::EFAULT],
        ktest: &[],
        ptrs: &[
            Ptr { arg: 3, name: "arg", kind: PtrKind::Cstr, out: false, nullable: false, len_from: None, size: 0 },
        ],
    },
    Call {
        sys: Sys::Getdents64,
        errors: &[Errno::EBADF, Errno::ENOTDIR, Errno::EINVAL, Errno::EFAULT],
        ktest: &[],
        ptrs: &[
            Ptr { arg: 1, name: "dirent", kind: PtrKind::Buf, out: true, nullable: false, len_from: Some(2), size: 0 },
        ],
    },
    Call {
        sys: Sys::Psinfo,
        errors: &[Errno::EFAULT],
        ktest: &[],
        ptrs: &[
            Ptr { arg: 0, name: "buf", kind: PtrKind::Buf, out: true, nullable: false, len_from: Some(1), size: 0 },
        ],
    },
    Call {
        sys: Sys::Openat,
        errors: &[Errno::EBADF, Errno::EFAULT, Errno::ENAMETOOLONG, Errno::EINVAL, Errno::ENOENT, Errno::ENOTDIR, Errno::EISDIR, Errno::EEXIST, Errno::EACCES, Errno::ELOOP, Errno::EMFILE, Errno::ENFILE, Errno::ENOSPC, Errno::ENOMEM, Errno::EIO],
        ktest: &[(Errno::EIO, "fat_bad_sector_eio"), (Errno::ENOMEM, "kalloc_nomem")],
        ptrs: &[
            Ptr { arg: 1, name: "filename", kind: PtrKind::Cstr, out: false, nullable: false, len_from: None, size: 0 },
        ],
    },
    Call {
        sys: Sys::Dup3,
        errors: &[Errno::EBADF, Errno::EINVAL],
        ktest: &[],
        ptrs: &[
        ],
    },
    Call {
        sys: Sys::Clone,
        errors: &[Errno::EAGAIN, Errno::ENOMEM, Errno::EINVAL],
        ktest: &[(Errno::ENOMEM, "fork_oom")],
        ptrs: &[
        ],
    },
];
