// @generated by scripts/gen_syscalls.py from crates/core/src/proc/syscalls.toml.
// Do not edit: change the table and run the script (ROADMAP §10.5).

//! The x86_64 syscall numbers, the table dispatch indexes, and the typed
//! `call`/`dispatch` (SYSCALL.md §1, §3): the pure half of the `SyscallAbi`
//! row (PORTABILITY §11.1). The number is `eax` sign-extended.

use crate::kerror::KError;
use crate::proc::syscall_table::{Handlers, NrRule, NrTable, Sys, SysResult};

/// The x86_64 numbers.
pub mod nr {
    /// `read`.
    pub const SYS_READ: u64 = 0;
    /// `write`.
    pub const SYS_WRITE: u64 = 1;
    /// `open`.
    pub const SYS_OPEN: u64 = 2;
    /// `close`.
    pub const SYS_CLOSE: u64 = 3;
    /// `lseek`.
    pub const SYS_LSEEK: u64 = 8;
    /// `mmap`.
    pub const SYS_MMAP: u64 = 9;
    /// `munmap`.
    pub const SYS_MUNMAP: u64 = 11;
    /// `brk`.
    pub const SYS_BRK: u64 = 12;
    /// `sched_yield`.
    pub const SYS_SCHED_YIELD: u64 = 24;
    /// `dup`.
    pub const SYS_DUP: u64 = 32;
    /// `dup2`.
    pub const SYS_DUP2: u64 = 33;
    /// `getpid`.
    pub const SYS_GETPID: u64 = 39;
    /// `fork`.
    pub const SYS_FORK: u64 = 57;
    /// `execve`.
    pub const SYS_EXECVE: u64 = 59;
    /// `exit`.
    pub const SYS_EXIT: u64 = 60;
    /// `wait4`.
    pub const SYS_WAIT4: u64 = 61;
    /// `kill`.
    pub const SYS_KILL: u64 = 62;
    /// `fcntl`.
    pub const SYS_FCNTL: u64 = 72;
    /// `getppid`.
    pub const SYS_GETPPID: u64 = 110;
    /// `psinfo`.
    pub const SYS_PSINFO: u64 = 500;
}

const SLOTS: [Option<Sys>; 501] = {
    let mut t = [None; 501];
    t[nr::SYS_READ as usize] = Some(Sys::Read);
    t[nr::SYS_WRITE as usize] = Some(Sys::Write);
    t[nr::SYS_OPEN as usize] = Some(Sys::Open);
    t[nr::SYS_CLOSE as usize] = Some(Sys::Close);
    t[nr::SYS_LSEEK as usize] = Some(Sys::Lseek);
    t[nr::SYS_MMAP as usize] = Some(Sys::Mmap);
    t[nr::SYS_MUNMAP as usize] = Some(Sys::Munmap);
    t[nr::SYS_BRK as usize] = Some(Sys::Brk);
    t[nr::SYS_SCHED_YIELD as usize] = Some(Sys::SchedYield);
    t[nr::SYS_DUP as usize] = Some(Sys::Dup);
    t[nr::SYS_DUP2 as usize] = Some(Sys::Dup2);
    t[nr::SYS_GETPID as usize] = Some(Sys::Getpid);
    t[nr::SYS_FORK as usize] = Some(Sys::Fork);
    t[nr::SYS_EXECVE as usize] = Some(Sys::Execve);
    t[nr::SYS_EXIT as usize] = Some(Sys::Exit);
    t[nr::SYS_WAIT4 as usize] = Some(Sys::Wait4);
    t[nr::SYS_KILL as usize] = Some(Sys::Kill);
    t[nr::SYS_FCNTL as usize] = Some(Sys::Fcntl);
    t[nr::SYS_GETPPID as usize] = Some(Sys::Getppid);
    t[nr::SYS_PSINFO as usize] = Some(Sys::Psinfo);
    t
};

/// The table dispatch indexes by number.
pub static TABLE: NrTable = NrTable::new(NrRule::SignExtendEax, &SLOTS);

/// Call `sys`'s handler, each register cut to its argument's C type.
pub fn call<H: Handlers + ?Sized>(h: &mut H, sys: Sys, regs: &[u64; 6]) -> SysResult {
    match sys {
        Sys::Read => h.read(regs[0] as u32, regs[1], regs[2] as usize),
        Sys::Write => h.write(regs[0] as u32, regs[1], regs[2] as usize),
        Sys::Open => h.open(regs[0], regs[1] as i32, regs[2] as u16),
        Sys::Close => h.close(regs[0] as u32),
        Sys::Lseek => h.lseek(regs[0] as u32, regs[1] as i64, regs[2] as u32),
        Sys::Mmap => h.mmap(regs[0], regs[1], regs[2], regs[3], regs[4], regs[5]),
        Sys::Munmap => h.munmap(regs[0], regs[1] as usize),
        Sys::Brk => h.brk(regs[0]),
        Sys::SchedYield => h.sched_yield(),
        Sys::Dup => h.dup(regs[0] as u32),
        Sys::Dup2 => h.dup2(regs[0] as u32, regs[1] as u32),
        Sys::Getpid => h.getpid(),
        Sys::Fork => h.fork(),
        Sys::Execve => h.execve(regs[0], regs[1], regs[2]),
        Sys::Exit => h.exit(regs[0] as i32),
        Sys::Wait4 => h.wait4(regs[0] as i32, regs[1], regs[2] as i32, regs[3]),
        Sys::Kill => h.kill(regs[0] as i32, regs[1] as i32),
        Sys::Fcntl => h.fcntl(regs[0] as u32, regs[1] as u32, regs[2]),
        Sys::Getppid => h.getppid(),
        Sys::Psinfo => h.psinfo(regs[0], regs[1] as usize),
    }
}

/// Look `raw_nr` up as Linux reads it and call its handler; a
/// number that names no row is `ENOSYS`.
pub fn dispatch<H: Handlers + ?Sized>(h: &mut H, raw_nr: u64, regs: &[u64; 6]) -> SysResult {
    match TABLE.lookup(raw_nr) {
        Some(sys) => call(h, sys, regs),
        None => Err(KError::ENOSYS),
    }
}
