#!/usr/bin/env python3
"""One `KError` holds the Linux errno mapping (ROADMAP §10.4, E2, C-KERROR).

Reads the Rust files under `src/`, `crates/`, `user/` and `tests/hostlib/`
that `git ls-files -co --exclude-standard` lists, and fails on:

(a) a `const`, an associated const included, named for a Linux errno (the
    asm-generic names errno(3) lists, such as `EINVAL`), outside
    `crates/core/src/kerror.rs` and files that start with the generated
    header `scripts/gen_syscalls.py` writes;
(b) an `enum` or `struct` named `*Error` in `crates/core/src/` or `src/`, or
    a type `EXTRA_ERRORS` names, without an `impl From<…Name> for KError`
    in those trees; test code (`#[cfg(test)]` modules, `tests.rs`, and
    `ktest` files) and type aliases do not count;
(c) an `impl From<…> for KError` whose body has a `_ =>` arm: each maps
    every variant by name, so a new variant needs its errno chosen.

A later errno is a new row of the `KError` table, never a `const`.
"""

from __future__ import annotations

import re
import subprocess
import sys
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TREES = ("src", "crates", "user", "tests/hostlib")
ERROR_TREES = ("crates/core/src", "src")
KERROR = "crates/core/src/kerror.rs"
GENERATED = "@generated by scripts/gen_syscalls.py"

# Error types whose names do not end in `Error`, each of which needs its
# `From` too.
EXTRA_ERRORS = ("Dead", "Fault", "IpiRefused")

# The asm-generic errno names, from errno(3) and `include/uapi/asm-generic/
# errno-base.h` and `errno.h`: names only.
ERRNO_NAMES = frozenset(
    """
    EPERM ENOENT ESRCH EINTR EIO ENXIO E2BIG ENOEXEC EBADF ECHILD EAGAIN ENOMEM EACCES EFAULT
    ENOTBLK EBUSY EEXIST EXDEV ENODEV ENOTDIR EISDIR EINVAL ENFILE EMFILE ENOTTY ETXTBSY EFBIG
    ENOSPC ESPIPE EROFS EMLINK EPIPE EDOM ERANGE EDEADLK ENAMETOOLONG ENOLCK ENOSYS ENOTEMPTY
    ELOOP EWOULDBLOCK ENOMSG EIDRM ECHRNG EL2NSYNC EL3HLT EL3RST ELNRNG EUNATCH ENOCSI EL2HLT
    EBADE EBADR EXFULL ENOANO EBADRQC EBADSLT EDEADLOCK EBFONT ENOSTR ENODATA ETIME ENOSR
    ENONET ENOPKG EREMOTE ENOLINK EADV ESRMNT ECOMM EPROTO EMULTIHOP EDOTDOT EBADMSG EOVERFLOW
    ENOTUNIQ EBADFD EREMCHG ELIBACC ELIBBAD ELIBSCN ELIBMAX ELIBEXEC EILSEQ ERESTART ESTRPIPE
    EUSERS ENOTSOCK EDESTADDRREQ EMSGSIZE EPROTOTYPE ENOPROTOOPT EPROTONOSUPPORT
    ESOCKTNOSUPPORT EOPNOTSUPP ENOTSUP EPFNOSUPPORT EAFNOSUPPORT EADDRINUSE EADDRNOTAVAIL
    ENETDOWN ENETUNREACH ENETRESET ECONNABORTED ECONNRESET ENOBUFS EISCONN ENOTCONN ESHUTDOWN
    ETOOMANYREFS ETIMEDOUT ECONNREFUSED EHOSTDOWN EHOSTUNREACH EALREADY EINPROGRESS ESTALE
    EUCLEAN ENOTNAM ENAVAIL EISNAM EREMOTEIO EDQUOT ENOMEDIUM EMEDIUMTYPE ECANCELED ENOKEY
    EKEYEXPIRED EKEYREVOKED EKEYREJECTED EOWNERDEAD ENOTRECOVERABLE ERFKILL EHWPOISON
    """.split()
)

CONST = re.compile(r"\bconst\s+([A-Z][A-Z0-9_]*)\s*:")
TYPE = re.compile(
    r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:enum|struct)\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.M
)
FROM_IMPL = re.compile(
    r"\bimpl\s+From<\s*(?:[A-Za-z_][A-Za-z0-9_]*::)*([A-Za-z_][A-Za-z0-9_]*)\s*>\s+for\s+"
    r"(?:[A-Za-z_][A-Za-z0-9_]*::)*KError\s*\{"
)
WILD_ARM = re.compile(r"(?:^|\|)\s*_\s*(?:if\b[^=]*)?=>", re.M)
TEST_MOD = re.compile(r"^\s*#\[cfg\(test\)\]\s*\n\s*(?:pub(?:\([^)]*\))?\s+)?mod\s", re.M)


def listed_files(root: Path = ROOT) -> list[str]:
    """Tracked and untracked, non-ignored Rust files under TREES."""
    out = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z", "-co", "--exclude-standard", "--", *TREES],
        capture_output=True,
        check=True,
    ).stdout
    paths = {p.decode("utf-8", errors="surrogateescape") for p in out.split(b"\0") if p}
    return sorted(p for p in paths if p.endswith(".rs"))


def strip_comments(text: str) -> str:
    """`text` without `//` comments, so a comment naming a const is not one."""
    return "\n".join(re.sub(r"//.*$", "", ln) for ln in text.splitlines())


def is_generated(text: str) -> bool:
    first = text.split("\n", 1)[0]
    return GENERATED in first


def is_test_file(path: str) -> bool:
    parts = path.split("/")
    name = parts[-1]
    return (
        name == "tests.rs"
        or any(p == "ktest" or p.startswith("ktest") for p in parts[:-1])
        or (name.startswith("ktest") and name.endswith(".rs"))
    )


def non_test(text: str) -> str:
    """`text` up to its first `#[cfg(test)] mod`, which runs to the file's end."""
    m = TEST_MOD.search(text)
    return text if m is None else text[: m.start()]


def rule_a(path: str, text: str) -> list[str]:
    if path == KERROR or is_generated(text):
        return []
    errors = []
    for n, line in enumerate(strip_comments(text).splitlines(), start=1):
        for m in CONST.finditer(line):
            if m.group(1) in ERRNO_NAMES:
                errors.append(
                    f"{path}:{n}: const {m.group(1)} is named for a Linux errno; "
                    "use the KError table (vibeos::kerror)"
                )
    return errors


def body_at(text: str, open_brace: int) -> str:
    """The text between the `{` at `open_brace` and its matching `}`."""
    depth = 0
    for i in range(open_brace, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace + 1 : i]
    return text[open_brace + 1 :]


def from_impls(path: str, text: str) -> tuple[set[str], list[str]]:
    """The error types `text` converts into KError, and rule (c)'s errors."""
    names: set[str] = set()
    errors: list[str] = []
    code = strip_comments(text)
    for m in FROM_IMPL.finditer(code):
        names.add(m.group(1))
        body = body_at(code, m.end() - 1)
        if WILD_ARM.search(body):
            line = code.count("\n", 0, m.start()) + 1
            errors.append(
                f"{path}:{line}: impl From<{m.group(1)}> for KError has a `_ =>` arm; "
                "map each variant by name"
            )
    return names, errors


def check(files: Iterable[tuple[str, str]], found: set[str] | None = None) -> list[str]:
    """Every rule's errors over `(path, text)` pairs; `found` collects the error types."""
    errors: list[str] = []
    defined: dict[str, str] = {}
    converted: set[str] = set()
    for path, text in files:
        errors.extend(rule_a(path, text))
        in_error_trees = any(path.startswith(t + "/") for t in ERROR_TREES)
        if not in_error_trees or is_test_file(path):
            continue
        code = non_test(strip_comments(text))
        for m in TYPE.finditer(code):
            name = m.group(1)
            if name.endswith("Error") or name in EXTRA_ERRORS:
                line = code.count("\n", 0, m.start()) + 1
                defined.setdefault(name, f"{path}:{line}")
        names, errs = from_impls(path, non_test(text))
        converted |= names
        errors.extend(errs)
    if found is not None:
        found |= set(defined)
    for name in sorted(set(defined) - converted - {"KError"}):
        errors.append(f"{defined[name]}: {name} has no `impl From<{name}> for KError`")
    for name in EXTRA_ERRORS:
        if name not in defined:
            errors.append(f"check_errors.py: EXTRA_ERRORS names {name}, which no file defines")
    return errors


def read_files(root: Path, paths: Iterable[str]) -> list[tuple[str, str]]:
    out = []
    for p in paths:
        try:
            out.append((p, (root / p).read_text(encoding="utf-8")))
        except (OSError, UnicodeDecodeError):
            continue  # listed but deleted from the working tree, or not text
    return out


def main(argv: list[str] | None = None) -> int:
    del argv
    try:
        paths = listed_files(ROOT)
    except (OSError, subprocess.CalledProcessError) as e:
        print(f"check_errors: git ls-files failed: {e}", file=sys.stderr)
        return 1
    found: set[str] = set()
    errors = check(read_files(ROOT, paths), found)
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    print(f"check_errors: ok ({len(paths)} files, {len(found)} error types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
