#!/usr/bin/env python3
"""Emit the kernel's ksyms table from a kernel ELF (DESIGN §2.5, §9.1).

The Makefile's `KERNEL_VARIANT` links twice: the first link has an empty
table, this script fills it from that ELF's `nm`, and the second link builds
it in. The table is a `#[used]` static in its own `.ksyms` section, which no
kernel code names: `log::ksyms::lookup` reaches it only through `linker.ld`'s
`__ksyms_start` and `__ksyms_end`, so the code that reads it is the same size
empty and filled and the second link leaves `.text` in place.

`--check ELF TABLE` regenerates the table from the final ELF and fails when
it differs from TABLE, the one that ELF linked.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

# Keep names short enough for a panic line.
NAME_MAX = 80
SKIP_PREFIXES = ("$", ".L", "__dso", "anon.")
# ThinLTO's promoted-local suffix, ` (.llvm.<hash>)` once demangled. The hash
# covers the module, and the kernel crate's module holds the table itself, so
# it differs between the two links while the address does not.
LLVM_SUFFIX = re.compile(r"(?: \(\.llvm\.\d+\)|\.llvm\.\d+)$")
HEADER = "// Generated by scripts/gen_ksyms.py. Do not edit.\n"


def rust_string(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("?")
    return '"' + "".join(out) + '"'


def skip_name(name: str) -> bool:
    if not name or name in (".text", "start"):
        return True
    # Keep the panic_handler; drop other compiler-rt names.
    if name.startswith("__rustc") and "rust_begin_unwind" not in name:
        return True
    for p in SKIP_PREFIXES:
        if name.startswith(p):
            return True
    return False


def parse_nm(text: str) -> list[tuple[int, str]]:
    """Function symbols sorted by (address, name), one per address.

    nm's order among symbols at one address is not specified, so the sort
    comes first and the lowest name at each address is the one kept.
    """
    found: list[tuple[int, str]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        # addr type name
        m = re.match(r"^([0-9a-fA-F]+)\s+([A-Za-z])\s+(.+)$", line)
        if not m:
            continue
        if m.group(2) not in "TtWw":
            continue
        addr = int(m.group(1), 16)
        name = m.group(3).strip()
        if addr == 0 or skip_name(name):
            continue
        name = LLVM_SUFFIX.sub("", name)
        if len(name) > NAME_MAX:
            name = name[: NAME_MAX - 3] + "..."
        found.append((addr, name))
    found.sort()
    entries: list[tuple[int, str]] = []
    for addr, name in found:
        if entries and entries[-1][0] == addr:
            continue
        entries.append((addr, name))
    return entries


def render(entries: list[tuple[int, str]]) -> str:
    """The Rust source `log::ksyms` includes for `entries`."""
    lines = [
        HEADER,
        "#[used]\n",
        '#[unsafe(link_section = ".ksyms")]\n',
        f"static KSYMS: [vibeos::symtab::Entry; {len(entries)}] = [\n",
    ]
    for addr, name in entries:
        lines.append(
            f"    vibeos::symtab::Entry {{ addr: {addr:#x}, name: {rust_string(name)} }},\n"
        )
    lines.append("];\n")
    return "".join(lines)


def check(rendered: str, linked: str) -> str | None:
    """None when the tables match, else the first line that differs."""
    if rendered == linked:
        return None
    new = rendered.splitlines()
    old = linked.splitlines()
    for i, (a, b) in enumerate(zip(new, old, strict=False), start=1):
        if a != b:
            return f"line {i}: linked {b.strip()!r}, final ELF {a.strip()!r}"
    n = min(len(new), len(old)) + 1
    if len(new) > len(old):
        return f"line {n}: final ELF adds {new[n - 1].strip()!r}"
    return f"line {n}: final ELF drops {old[n - 1].strip()!r}"


def nm_entries(nm: str, elf: str) -> list[tuple[int, str]] | None:
    cmd = [nm, "--demangle", "-n", "--defined-only", elf]
    try:
        proc = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"gen_ksyms: {cmd} failed: {e}", file=sys.stderr)
        if isinstance(e, subprocess.CalledProcessError):
            sys.stderr.write(e.stderr or "")
        return None
    return parse_nm(proc.stdout)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--nm", default=os.environ.get("NM", "nm"))
    ap.add_argument("--check", action="store_true",
                    help="fail unless TABLE matches the table ELF's symbols give")
    ap.add_argument("elf")
    ap.add_argument("table")
    args = ap.parse_args(argv)

    entries = nm_entries(args.nm, args.elf)
    if entries is None:
        return 1
    rendered = render(entries)

    if args.check:
        try:
            with open(args.table, encoding="utf-8") as f:
                linked = f.read()
        except OSError as e:
            print(f"gen_ksyms: {args.table}: {e}", file=sys.stderr)
            return 1
        diff = check(rendered, linked)
        if diff is not None:
            print(
                f"gen_ksyms: {args.elf}: table differs from the one it linked "
                f"({args.table}): {diff}",
                file=sys.stderr,
            )
            return 1
        print(f"gen_ksyms: {args.elf}: table matches ({len(entries)} symbols)", file=sys.stderr)
        return 0

    os.makedirs(os.path.dirname(os.path.abspath(args.table)) or ".", exist_ok=True)
    tmp = args.table + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(rendered)
    os.replace(tmp, args.table)
    print(f"gen_ksyms: {len(entries)} symbols -> {args.table}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
