#!/usr/bin/env python3
"""Emit a sorted ksyms table from a kernel ELF. Used by the Makefile two-pass."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

# Keep names short enough for a panic line.
NAME_MAX = 80
SKIP_PREFIXES = ("$", ".L", "__dso", "anon.")


def rust_string(s: str) -> str:
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("?")
    return '"' + "".join(out) + '"'


def skip_name(name: str) -> bool:
    if not name or name in (".text", "start"):
        return True
    # Keep the panic_handler; drop other compiler-rt names.
    if name.startswith("__rustc") and "rust_begin_unwind" not in name:
        return True
    for p in SKIP_PREFIXES:
        if name.startswith(p):
            return True
    return False


def parse_nm(text: str) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []
    seen: set[int] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        # addr type name
        m = re.match(r"^([0-9a-fA-F]+)\s+([A-Za-z])\s+(.+)$", line)
        if not m:
            continue
        kind = m.group(2)
        if kind not in "TtWw":
            continue
        addr = int(m.group(1), 16)
        if addr == 0 or addr in seen:
            continue
        name = m.group(3).strip()
        if skip_name(name):
            continue
        if len(name) > NAME_MAX:
            name = name[: NAME_MAX - 3] + "..."
        seen.add(addr)
        entries.append((addr, name))
    entries.sort(key=lambda x: x[0])
    return entries


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--nm", default=os.environ.get("NM", "nm"))
    ap.add_argument("elf")
    ap.add_argument("out")
    args = ap.parse_args()

    cmd = [args.nm, "--demangle", "-n", "--defined-only", args.elf]
    try:
        proc = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"gen_ksyms: {cmd} failed: {e}", file=sys.stderr)
        if isinstance(e, subprocess.CalledProcessError):
            sys.stderr.write(e.stderr or "")
        return 1

    entries = parse_nm(proc.stdout)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    tmp = args.out + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/gen_ksyms.py. Do not edit.\n")
        f.write("pub static KSYMS: &[vibeos::symtab::Entry] = &[\n")
        for addr, name in entries:
            f.write(
                f"    vibeos::symtab::Entry {{ addr: {addr:#x}, name: {rust_string(name)} }},\n"
            )
        f.write("];\n")
    os.replace(tmp, args.out)
    print(f"gen_ksyms: {len(entries)} symbols -> {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
