// @generated by scripts/gen_syscalls.py from crates/core/src/kerror.rs.
// Do not edit: change the table and run the script (ROADMAP §10.4).

//! Linux's errno values, as the kernel's `KError` table defines them
//! (C-KERROR): `Errno::EBADF` is what a call that fails with `EBADF`
//! returns.

use crate::sys::Errno;

impl Errno {
    /// Linux `EPERM`.
    pub const EPERM: Errno = Errno(1);
    /// Linux `ENOENT`.
    pub const ENOENT: Errno = Errno(2);
    /// Linux `ESRCH`.
    pub const ESRCH: Errno = Errno(3);
    /// Linux `EIO`.
    pub const EIO: Errno = Errno(5);
    /// Linux `ENXIO`.
    pub const ENXIO: Errno = Errno(6);
    /// Linux `E2BIG`.
    pub const E2BIG: Errno = Errno(7);
    /// Linux `ENOEXEC`.
    pub const ENOEXEC: Errno = Errno(8);
    /// Linux `EBADF`.
    pub const EBADF: Errno = Errno(9);
    /// Linux `ECHILD`.
    pub const ECHILD: Errno = Errno(10);
    /// Linux `EAGAIN`.
    pub const EAGAIN: Errno = Errno(11);
    /// Linux `ENOMEM`.
    pub const ENOMEM: Errno = Errno(12);
    /// Linux `EACCES`.
    pub const EACCES: Errno = Errno(13);
    /// Linux `EFAULT`.
    pub const EFAULT: Errno = Errno(14);
    /// Linux `EBUSY`.
    pub const EBUSY: Errno = Errno(16);
    /// Linux `EEXIST`.
    pub const EEXIST: Errno = Errno(17);
    /// Linux `EXDEV`.
    pub const EXDEV: Errno = Errno(18);
    /// Linux `ENODEV`.
    pub const ENODEV: Errno = Errno(19);
    /// Linux `ENOTDIR`.
    pub const ENOTDIR: Errno = Errno(20);
    /// Linux `EISDIR`.
    pub const EISDIR: Errno = Errno(21);
    /// Linux `EINVAL`.
    pub const EINVAL: Errno = Errno(22);
    /// Linux `ENFILE`.
    pub const ENFILE: Errno = Errno(23);
    /// Linux `EMFILE`.
    pub const EMFILE: Errno = Errno(24);
    /// Linux `EFBIG`.
    pub const EFBIG: Errno = Errno(27);
    /// Linux `ENOSPC`.
    pub const ENOSPC: Errno = Errno(28);
    /// Linux `ESPIPE`.
    pub const ESPIPE: Errno = Errno(29);
    /// Linux `EROFS`.
    pub const EROFS: Errno = Errno(30);
    /// Linux `ENAMETOOLONG`.
    pub const ENAMETOOLONG: Errno = Errno(36);
    /// Linux `ENOSYS`.
    pub const ENOSYS: Errno = Errno(38);
    /// Linux `ENOTEMPTY`.
    pub const ENOTEMPTY: Errno = Errno(39);
    /// Linux `ELOOP`.
    pub const ELOOP: Errno = Errno(40);
    /// Linux `EOPNOTSUPP`.
    pub const EOPNOTSUPP: Errno = Errno(95);
}
